.data

.globl CG_DrawPlayerStance_rectDef_s_const___float___Font_s___float__int___C.180
CG_DrawPlayerStance_rectDef_s_const___float___Font_s___float__int___C.180:
    .space 256

.globl CG_DrawPlayerStance_rectDef_s_const___float___Font_s___float__int___C.181
CG_DrawPlayerStance_rectDef_s_const___float___Font_s___float__int___C.181:
    .space 256

.globl CG_DrawPlayerStance_rectDef_s_const___float___Font_s___float__int___C.182
CG_DrawPlayerStance_rectDef_s_const___float___Font_s___float__int___C.182:
    .space 256

.globl _ZN11FxBoltFrame12g_mFrameListE
_ZN11FxBoltFrame12g_mFrameListE:
    .space 256

.globl _ZTV5Cloud
_ZTV5Cloud:
    .space 256

.globl _ZTV8Cylinder
_ZTV8Cylinder:
    .space 256

.globl _ZTV6Effect
_ZTV6Effect:
    .space 256

.globl _ZTV7Emitter
_ZTV7Emitter:
    .space 256

.globl _ZTV5Light
_ZTV5Light:
    .space 256

.globl _ZTV4Line
_ZTV4Line:
    .space 256

.globl _ZTV16OrientedParticle
_ZTV16OrientedParticle:
    .space 256

.globl _ZTV8Particle
_ZTV8Particle:
    .space 256

.globl _ZTV4Tail
_ZTV4Tail:
    .space 256

.globl _ZZ19CG_DrawPlayerStancePK10rectDef_sPfP6Font_sfiE5C.180
_ZZ19CG_DrawPlayerStancePK10rectDef_sPfP6Font_sfiE5C.180:
    .space 64

.globl _ZZ19CG_DrawPlayerStancePK10rectDef_sPfP6Font_sfiE5C.181
_ZZ19CG_DrawPlayerStancePK10rectDef_sPfP6Font_sfiE5C.181:
    .space 64

.globl _ZZ19CG_DrawPlayerStancePK10rectDef_sPfP6Font_sfiE5C.182
_ZZ19CG_DrawPlayerStancePK10rectDef_sPfP6Font_sfiE5C.182:
    .space 64

.text
.globl .Lf17fea4_0017ffad
.Lf17fea4_0017ffad:
    ret

.globl .Lf1d91a4_001d92d4
.Lf1d91a4_001d92d4:
    ret
