#ifndef CLEAN_PC_SCRIPT_SCR_FUNCS_H
#define CLEAN_PC_SCRIPT_SCR_FUNCS_H

#include "common_types.h"

#ifndef SCR_FUNCS_VM_LOCAL_VAR_ARCHIVE_DEFINED
#define SCR_FUNCS_VM_LOCAL_VAR_ARCHIVE_DEFINED
#ifndef VM_LOCAL_ARCHIVE_MAX_LOCALS
#define VM_LOCAL_ARCHIVE_MAX_LOCALS 64u
#endif
typedef struct VM_LocalVarArchive_s {
    unsigned int localId;
    unsigned int count;
    unsigned short vars[VM_LOCAL_ARCHIVE_MAX_LOCALS];
} VM_LocalVarArchive;
#endif

void SetAnimCheck(int bAnimCheck);
struct XAnim_s *Scr_GetAnims(int index);
void Scr_UsingTree(const char *filename, unsigned int sourcePos);
struct scr_animtree_t Scr_FindAnimTree(const char *filename);
void *Scr_FindAnimTree_asm(const char *filename);
void Scr_FindAnim(const char *filename, const char *animName, scr_anim_t *anim, int user);
void Scr_EmitAnimation(char *pos, unsigned int animName, unsigned int sourcePos);
void Scr_LoadAnimTreeAtIndex(int index, Alloc_t Alloc, int user);

int CompareCaseInfo(const unsigned int *elem1, const unsigned int *elem2);
void Scr_CompileShutdown(void);
void ScriptCompile(sval_t val, unsigned int fileId, unsigned int scriptId);

void DumpCompiledObject(const char *label, unsigned int compiledObj);
int Scr_IsInOpcodeMemory(const char *pos);
Bool Scr_IsIdentifier(const char *token);
unsigned int SL_TransferToCanonicalString(unsigned int stringValue);
void Scr_BeginLoadAnimTrees(int user);
int Scr_ScanFile(char *buf, int max_size);
unsigned int Scr_LoadScript(const char *filename);
void Scr_PostCompileScripts(void);
void Scr_EndLoadScripts(void);
void Scr_PrecacheAnimTrees(Alloc_t Alloc, int user);
void Scr_EndLoadAnimTrees(void);
void Scr_FreeScripts(int sys);
scr_func_t Scr_GetFunctionHandle(const char *filename, const char *name);
void Scr_BeginLoadScripts(void);
unsigned int SL_GetCanonicalString(const char *str);

int MT_IsNodeCovered(int nodeNum);
int MT_SearchTreeAny(int nodeNum);
void MT_VerifyNotInTree(int nodeNum);
unsigned int Scr_GetStringUsage(void);
byte *MT_InitForceAlloc(void);
void MT_Init(void);
void MT_DumpTree(void);
short unsigned int MT_AllocIndex(int numBytes, int type);
unsigned int *MT_Alloc(int numBytes, int type);
void MT_FreeIndex(unsigned int nodeNum, int numBytes);
void MT_Free(void *p, int numBytes);
int MT_Realloc(int oldNumBytes, int newNumbytes);
void MT_ForceAllocIndex(byte *allocBits, unsigned int nodeNum, int numBytes);
void MT_FinishForceAlloc(byte *allocBits);

void Scr_InitOpcodeLookup(void);
void Scr_ShutdownOpcodeLookup(void);
void AddOpcodePos(unsigned int sourcePos, int type);
void RemoveOpcodePos(void);
void AddThreadStartOpcodePos(unsigned int sourcePos);
int Scr_GetSourceBuffer(const char *codePos);
char *Scr_ReadFile(const char *filename, const char *extFilename, const char *codePos, int archive);
char *Scr_AddSourceBuffer(const char *filename, const char *extFilename, const char *codePos, unsigned char archive);
void CompileError(unsigned int sourcePos, const char *msg, ...);
void Scr_PrintPrevCodePos(print_msg_type_t type, const char *codePos, unsigned int index);
void RuntimeError(const char *codePos, unsigned int index, const char *msg, const char *dialogMessage);
void CompileError2(const char *codePos, const char *msg, ...);

uintptr_t node1_(uintptr_t val1);
uintptr_t node_pos(uintptr_t pos);
uintptr_t node0(int type);
uintptr_t node1(int type, uintptr_t val1);
uintptr_t node2(int type, uintptr_t val1, uintptr_t val2);
uintptr_t node2_(uintptr_t val1, uintptr_t val2);
uintptr_t node3(int type, uintptr_t val1, uintptr_t val2, uintptr_t val3);
uintptr_t node4(int type, uintptr_t val1, uintptr_t val2, uintptr_t val3, uintptr_t val4);
uintptr_t node5(int type, uintptr_t val1, uintptr_t val2, uintptr_t val3, uintptr_t val4, uintptr_t val5);
uintptr_t node6(int type, uintptr_t val1, uintptr_t val2, uintptr_t val3, uintptr_t val4, uintptr_t val5, uintptr_t val6);
uintptr_t node7(int type, uintptr_t val1, uintptr_t val2, uintptr_t val3, uintptr_t val4, uintptr_t val5, uintptr_t val6, uintptr_t val7);
uintptr_t node8(int type, uintptr_t val1, uintptr_t val2, uintptr_t val3, uintptr_t val4, uintptr_t val5, uintptr_t val6, uintptr_t val7, uintptr_t val8);
uintptr_t linked_list_end(uintptr_t val);
uintptr_t prepend_node(uintptr_t val1, uintptr_t val2);
uintptr_t append_node(uintptr_t val1, uintptr_t val2);

unsigned int SL_ConvertFromString(const char *str);
void SL_Shutdown(void);
const char *SL_ConvertToString(unsigned int stringValue);
void SL_TransferRefToUser(unsigned int stringValue, unsigned int user);
void DBG_PrintTransferStats(void);
void SL_AddRefToString(unsigned int stringValue);
void SL_RemoveRefToStringOfLen(unsigned int stringValue, unsigned int len);
int SL_GetStringLen(unsigned int stringValue);
unsigned int SL_FindStringOfLen(const char *str, unsigned int len);
unsigned int SL_FindLowercaseString(const char *str);
unsigned int SL_FindString(const char *str);
unsigned int SL_GetStringOfLen(const char *str, unsigned int user, unsigned int len, int type);
unsigned int SL_GetLowercaseString_(const char *str, unsigned int user, int type);
unsigned int SL_GetString_(const char *str, unsigned int user, int type);
void SL_RemoveRefToString(unsigned int stringValue);
void SL_ShutdownSystem(unsigned int user);
void Scr_SetString(scr_string_t *to, unsigned int from);
unsigned int SL_ConvertToLowercase(unsigned int stringValue, unsigned int user, int type);
void Scr_ShutdownGameStrings(void);
void SL_Init(void);
unsigned int Scr_AllocString(const char *s, int sys);
unsigned int SL_GetString(const char *str, unsigned int user);
unsigned int SL_GetStringForFloat(float f);
unsigned int SL_GetStringForInt(int i);
unsigned int SL_GetStringForVector(const float *v);
unsigned int Scr_CreateCanonicalFilename(const char *filename);

void TempMemoryReset(void);
char *TempMalloc(int len);
char *TempMallocAlign(int len);
char *TempMallocAlignStrict(int len);
void TempMemorySetPos(char *pos);

int GetVarType(unsigned int id);
void FreeVariable(unsigned int id);
unsigned int FindNextSibling(unsigned int id);
void Scr_DumpScriptVariables(void);
void Scr_DumpScriptVarSummary(void);
void Var_Init(void);
unsigned int Scr_GetNumScriptVars(void);
unsigned int GetVariableKeyObject(unsigned int id);
void AddRefToObject(unsigned int id);
void Scr_SetThreadNotifyName(unsigned int startLocalId, unsigned int stringValue);
short unsigned int Scr_GetThreadNotifyName(unsigned int startLocalId);
void Scr_SetThreadWaitTime(unsigned int startLocalId, unsigned int waitTime);
void Scr_ClearWaitTime(unsigned int startLocalId);
unsigned int Scr_GetThreadWaitTime(unsigned int startLocalId);
unsigned int GetParentLocalId(unsigned int threadId);
unsigned int GetSafeParentLocalId(unsigned int threadId);
unsigned int GetStartLocalId(unsigned int threadId);
unsigned int FindObject(unsigned int id);
VariableUnion *GetVariableValueAddress(unsigned int id);
void RemoveRefToEmptyObject(unsigned int id);
unsigned int Scr_GetSelf(unsigned int threadId);
void RemoveRefToVector(const float *vectorValue);
Bool IsValidArrayIndex(unsigned int unsignedValue);
unsigned int GetInternalVariableIndex(unsigned int unsignedValue);
void SetNewVariableValue(unsigned int id, VariableValue *value);
unsigned int Scr_EvalVariableObject(unsigned int id);
unsigned int GetArraySize(unsigned int id);
unsigned int FindPrevSibling(unsigned int id);
unsigned int GetVariableName(unsigned int id);
Bool IsFieldObject(unsigned int id);
Bool IsVarFree(unsigned int id);
unsigned int Scr_GetEntityIdRef(unsigned int entId);
unsigned int Scr_FindField(const char *name, int *type);
int Scr_GetClassnumForCharId(int charId);
void Scr_RemoveThreadNotifyName(unsigned int startLocalId);
void AddRefToValue(int type, VariableUnion u);
const float *Scr_AllocVector(const float *v);
int Scr_GetOffset(int classnum, const char *name);
unsigned int FindEntityId(int entnum, int classnum);
unsigned int FindArrayVariable(unsigned int parentId, int intValue);
unsigned int FindVariable(unsigned int parentId, unsigned int index);
unsigned int FindObjectVariable(unsigned int parentId, unsigned int id);
void Scr_AddFields(const char *path, const char *extension);
unsigned long long Scr_EvalVariable(unsigned int id);
unsigned int GetNewObjectVariableReverse(unsigned int parentId, unsigned int id);
unsigned int GetNewObjectVariable(unsigned int parentId, unsigned int id);
void SetVariableEntityFieldValue(unsigned int entId, unsigned int fieldName, VariableValue *value);
void Scr_AddClassField(int classnum, const char *name, unsigned int offset);
unsigned int GetNewArrayVariable(unsigned int parentId, unsigned int unsignedValue);
unsigned int GetNewVariable(unsigned int parentId, unsigned int unsignedValue);
void Scr_DumpScriptThreads(void);
unsigned int Scr_GetEntityId(int entnum, int classnum);
unsigned int Scr_EvalArrayIndex(unsigned int parentId, VariableValue *index);
unsigned int Scr_GetVariableField(unsigned int parentId, unsigned int name);
unsigned int GetArrayVariable(unsigned int parentId, unsigned int unsignedValue);
unsigned int GetVariable(unsigned int parentId, unsigned int unsignedValue);
unsigned int GetObjectVariable(unsigned int parentId, unsigned int id);
void Scr_SetClassMap(int classnum);
unsigned int GetArray(unsigned int id);
unsigned int GetObjectA(unsigned int id);
unsigned int AllocValue(void);
unsigned int AllocObject(void);
unsigned int Scr_AllocArray(void);
unsigned int AllocThread(unsigned int self);
unsigned int AllocChildThread(unsigned int self, unsigned int parentLocalId);
void RemoveRefToObject(unsigned int id);
void Scr_FreeValue(unsigned int id);
void Scr_EvalArray(VariableValue *value, VariableValue *index);
void Scr_RemoveClassMap(int classnum);
unsigned long long Scr_EvalVariableField(unsigned int id);
unsigned long long Scr_FindVariableField(unsigned int parentId, unsigned int name);
void RemoveRefToValue(int type, VariableUnion u);
void Scr_KillEndonThread(unsigned int threadId);
void Scr_FreeEntityList(void);
void SafeRemoveVariable(unsigned int parentId, unsigned int unsignedValue);
void RemoveNextVariable(unsigned int parentId);
void RemoveVariable(unsigned int parentId, unsigned int unsignedValue);
void Scr_FreeGameVariable(int bComplete);
void Scr_FreeEntityNum(int entnum, int classnum);
void RemoveObjectVariable(unsigned int parentId, unsigned int id);
void ClearVariableField(unsigned int parentId, unsigned int name, VariableValue *value);
void Var_Shutdown(void);
void Scr_FreeObjects(void);
void Scr_EvalBoolNot(VariableValue *value);
void SetVariableFieldValue(unsigned int id, VariableValue *value);
void Scr_AllocGameVariable(void);
unsigned int Scr_EvalArrayRef(unsigned int parentId);
void Scr_StopThread(unsigned int threadId);
void ClearObjectInternal(unsigned int parentId);
void ClearObject(unsigned int id);
void Scr_KillThread(unsigned int parentId);
unsigned int Scr_EvalFieldObject(unsigned int tempVariable, VariableValue *value);
Bool Scr_CastString(VariableValue *value);
void Scr_CastDebugString(VariableValue *value);
void Scr_UnmatchingTypesError(VariableValue *value1, VariableValue *value2);
void Scr_EvalMod(VariableValue *value1, VariableValue *value2);
void Scr_EvalDivide(VariableValue *value1, VariableValue *value2);
void Scr_EvalPlus(VariableValue *value1, VariableValue *value2);
void Scr_EvalShiftRight(VariableValue *value1, VariableValue *value2);
void Scr_EvalShiftLeft(VariableValue *value1, VariableValue *value2);
void Scr_EvalAnd(VariableValue *value1, VariableValue *value2);
void Scr_EvalExOr(VariableValue *value1, VariableValue *value2);
void Scr_EvalOr(VariableValue *value1, VariableValue *value2);
void Scr_EvalLessEqual(VariableValue *value1, VariableValue *value2);
void Scr_EvalGreaterEqual(VariableValue *value1, VariableValue *value2);
void Scr_EvalEquality(VariableValue *value1, VariableValue *value2);
void Scr_EvalInequality(VariableValue *value1, VariableValue *value2);
void Scr_EvalLess(VariableValue *value1, VariableValue *value2);
void Scr_EvalGreater(VariableValue *value1, VariableValue *value2);
void Scr_EvalMinus(VariableValue *value1, VariableValue *value2);
void Scr_EvalBinaryOperator(int op, VariableValue *value1, VariableValue *value2);
void Scr_EvalMultiply(VariableValue *value1, VariableValue *value2);
void Scr_CastBool(VariableValue *value);
void Scr_EvalBoolComplement(VariableValue *value);
void Scr_EvalSizeValue(VariableValue *value);
void Scr_CastVector(VariableValue *value);
void FreeChildValue(unsigned int id);
void FreeValue(unsigned int id);
void SetVariableValue(unsigned int id, VariableValue *value);
void ClearVariableValue(unsigned int id);
void ClearArray(unsigned int parentId, VariableValue *value);

void Scr_ClearErrorMessage(void);
void Scr_Settings(int developer, int developer_script, int abort_on_error);
void Scr_Shutdown(void);
void Scr_Abort(void);
void Scr_SetLoading(int bLoading);
unsigned int Scr_GetNumScriptThreads(void);
void Scr_ResetTimeout(void);
void VM_CancelNotify(unsigned int notifyListOwnerId, unsigned int startLocalId);
void Scr_CancelNotifyList(unsigned int notifyListOwnerId);
void Scr_FreeThread(int handle);
void Scr_InitSystem(void);
void Scr_ShutdownSystem(int sys, int bComplete);
int Scr_IsSystemActive(int sys);
unsigned int Scr_GetNumParam(void);
void Scr_AddArray(void);
void Scr_AddArrayStringIndexed(unsigned int stringValue);
unsigned long long __attribute_regparm__(0) GetEntityFieldValue(unsigned int classnum, int entnum, int offset);
void Scr_SetStructField(unsigned int structId, unsigned int index);
void Scr_Init(void);
void Scr_TraverseScript(const char *pos);
const char *Scr_GetNextCodepos(VariableValue *top, const char *pos, int opcode, int mode, unsigned int *localId);
void Scr_SetDynamicEntityField(int entnum, int classnum, unsigned int index);
void Scr_MakeArray(void);
void Scr_NotifyNum(int entnum, int classnum, unsigned int stringValue, unsigned int paramcount);
Bool SetEntityFieldValue(unsigned int classnum, int entnum, int offset, VariableValue *value);
void Scr_ObjectError(const char *error);
void Scr_ParamError(unsigned int index, const char *error);
void Scr_TerminalError(const char *error);
int Scr_GetPointerType(unsigned int index);
const char *Scr_GetTypeName(unsigned int index);
int Scr_GetType(unsigned int index);
unsigned int Scr_GetObject(unsigned int index);
struct scr_entref_t Scr_GetEntityRef(unsigned int index);
void Scr_GetVector(unsigned int index, float *vectorValue);
const char *Scr_GetDebugString(unsigned int index);
float Scr_GetFloat(unsigned int index);
int Scr_GetInt(unsigned int index);
void Scr_RunCurrentThreads(void);
void Scr_IncTime(void);
__attribute__((noinline)) unsigned int __attribute_regparm__(3) VM_ExecuteExtCall(unsigned int threadId, const char *pos, unsigned int paramcount);
void Scr_AddExecThread(scr_func_t handle, unsigned int paramcount);
scr_thread_t Scr_ExecEntThreadNum(int entnum, int classnum, scr_func_t handle, unsigned int paramcount);
scr_thread_t Scr_ExecThread(scr_func_t handle, unsigned int numArgs);
const char *Scr_GetIString(unsigned int index);
scr_anim_t Scr_GetAnim(unsigned int index, struct XAnimTree_s *tree);
unsigned int Scr_GetConstString(unsigned int index);
unsigned int Scr_GetConstStringIncludeNull(unsigned int index);
const char *Scr_GetString(unsigned int index);
unsigned int Scr_GetConstLowercaseString(unsigned int index);
void Scr_Error(const char *error);
void Scr_AddStruct(void);
void Scr_AddEntityNum(int entnum, int classnum);
void Scr_AddBool(int value);
void Scr_AddInt(int value);
void Scr_AddFloat(float value);
void Scr_AddUndefined(void);
void Scr_AddObject(unsigned int id);
void Scr_AddString(const char *value);
void Scr_AddConstString(unsigned int value);
void Scr_AddVector(const float *value);

YY_BUFFER_STATE yy_create_buffer(FILE *file, int size);
void ScriptParse(sval_t *parseData, int user);

#endif
