#ifndef CLEAN_PC_UI_MP_UI_FUNCS_H
#define CLEAN_PC_UI_MP_UI_FUNCS_H

#include "common_types.h"
#include "bytematch.h"

#ifndef UI_REGPARM1
#  define UI_REGPARM1 __attribute__((regparm(1)))
#endif

void UI_DrawHandlePic(float x, float y, float w, float h, int horzAlign, int vertAlign, const vec_t *color, MaterialHandle hMaterial);
void UI_DrawLoadBar(float x, float y, float w, float h, int horzAlign, int vertAlign, const vec_t *color, MaterialHandle material);
void UI_FillRectPhysical(float x, float y, float width, float height, const vec_t *color);
void UI_FillRect(float x, float y, float width, float height, int horzAlign, int vertAlign, const vec_t *color);

int UI_ParseInfos(const char *buf, int max, char **infos);

void diag_drawtext(const char *text, void *font, float x, float y, float scale);
void UI_AssetCache(void);
void UI_DrawSides(float x, float y, float w, float h, int horzAlign, int vertAlign, float size, const vec_t *color);
void UI_DrawTopBottom(float x, float y, float w, float h, int horzAlign, int vertAlign, float size, const vec_t *color);
int UI_TextWidth(const char *text, int maxChars, FontHandle font, float scale);
int UI_TextHeight(FontHandle font, float scale);
FontHandle UI_GetFontHandle(int fontEnum, float scale);
void UI_UpdateTime(int realtime);
void UI_Shutdown(void);
char *GetMenuBuffer(const char *filename);
qboolean Load_ScriptMenu(const char *pszMenu, int imageTrack);
const char *UI_GetMapDisplayName(const char *pszMap);
const char *UI_GetMapDisplayNameFromPartialLoadNameMatch(const char *pszMap, int *mapLoadNameLen);
const char *UI_GetGameTypeDisplayName(const char *pszGameType);
void UI_BuildPlayerList(void);
void UI_DrawMapLevelshot(void);
void UI_LoadIngameMenus(void);
void UI_SetMap(const char *mapname, const char *gametype);
qboolean UI_OwnerDrawVisible(int flags);
qboolean UI_CheckExecKey(int key);
const char *UI_SafeTranslateString(const char *reference);
Bool UI_GetOpenOrCloseMenuOnDvarArgs(const char **args, const char *cmd, char *dvarName, char *testValue, char *menuName);
void UI_FeederSelection(float feederID, int index);
void UI_Pause(qboolean b);
void UI_OpenMenu_f(void);
void UI_CloseMenu_f(void);
void UI_Init(void);
void UI_KeyEvent(int key, qboolean down);
void UI_MouseEvent(int dx, int dy);
void UI_MouseEventAbsolute(int x, int y);
uiMenuCommand_t UI_GetActiveMenu(void);
qboolean UI_SetActiveMenu(int menu);
qboolean UI_IsFullscreen(void);
float UI_GetBlurRadius(void);
qboolean UI_AnyFullScreenMenuVisible(void);
const char *UI_ReplaceConversions(const char *sourceString, ConversionArguments *arguments);
const char *UI_ReplaceConversionString(const char *sourceString, const char *replaceString);
void UI_CloseAll(void);
void UI_CloseFocusedMenu(void);
void UI_OverrideCursorPos(rectDef_t (*item)[16]);
Bool UI_DrawRecordLevel(rectDef_t *rect);
MaterialHandle UI_FeederItemImage(const float feederID, int index);
void UI_DrawText(const char *text, int maxChars, FontHandle font, float x, float y, int horzAlign, int vertAlign, float scale, const vec_t *color, int style);
void UI_DrawTextWithCursor(const char *text, int maxChars, FontHandle font, float x, float y, int horzAlign, int vertAlign, float scale, const vec_t *color, int style, int cursorPos, int cursor);
qboolean UI_OwnerDrawHandleKey(int ownerDraw, int flags, float *special, int key);
const char *UI_FeederItemText(float feederID, int index, int column, MaterialHandle *handle);
void UI_DrawRect(float x, float y, float width, float height, int horzAlign, int vertAlign, float size, const vec_t *color);
int UI_OwnerDrawWidth(int ownerDraw, FontHandle font, float scale);
void UI_OwnerDraw(float x, float y, float w, float h, int horzAlign, int vertAlign, float text_x, float text_y, int ownerDraw, int ownerDrawFlags, int align, float special, FontHandle font, float scale, vec_t *color, MaterialHandle material, int textStyle);
void UI_Refresh(void);
void UI_RunMenuScript(const char **args);
int UI_FeederCount(float feederID);
void UI_DrawConnectScreen(void);

void diag_item_paint_enter(void *item);
void diag_item_paint_skip(void *item, int reason);
void diag_item_paint_draw(void *item);
void LerpColor(vec_t *a, vec_t *b, vec_t *c, float t);
qboolean String_Parse(const char **p, char *out, int len);
int Menu_ItemsMatchingGroup(menuDef_t *menu, const char *name);
itemDef_t *Menu_GetMatchingItemByNumber(menuDef_t *menu, int index, const char *name);
void Script_SetColor(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_SetBackground(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Menu_ShowItemByName(menuDef_t *menu, const char *p, qboolean bShow);
void Menu_FadeItemByName(menuDef_t *menu, const char *p, qboolean fadeOut);
menuDef_t *Menus_FindByName(displayContextDef_t *dc, const char *p);
void Script_Show(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_Hide(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_FadeIn(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_FadeOut(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_SetDvar(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_ExecNow(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_ExecOnDvarStringValue(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_ExecOnDvarIntValue(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_ExecOnDvarFloatValue(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_ExecNowOnDvarStringValue(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_ExecNowOnDvarIntValue(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_ExecNowOnDvarFloatValue(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_Play(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_ScriptMenuResponse(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Item_RunScript(displayContextDef_t *dc, itemDef_t *item, const char *s);
void Controls_GetConfig(void);
void Controls_SetConfig(qboolean restart);
void Controls_SetDefaults(void);
void BindingFromName(const char *dvar, char *nameBind);
qboolean GetCommandHasBinding(const char *command);
int GetKeyBindings(const char *command, char (*bindings)[128]);
int GetKeyBindingLocalizedString(const char *command, char *keys);
qboolean Display_KeyBindPending(void);
int Menu_Count(displayContextDef_t *dc);
void UI_AddMenuList(displayContextDef_t *dc, MenuList *menuList);
void Item_MouseLeave(displayContextDef_t *dc, itemDef_t *item);
float Item_Slider_ThumbPosition(itemDef_t *item);
qboolean Menu_CheckOnKey(displayContextDef_t *dc, menuDef_t *menu, int key);
qboolean Menus_AnyFullScreenVisible(displayContextDef_t *dc);
menuDef_t *Menu_GetFocused(displayContextDef_t *dc);
int Item_ListBox_MaxScroll(itemDef_t *item);
int Item_ListBox_ThumbPosition(itemDef_t *item);
int Item_ListBox_ThumbDrawPosition(displayContextDef_t *dc, itemDef_t *item);
void Menus_Close(displayContextDef_t *dc, menuDef_t *menu);
void Menus_CloseAll(displayContextDef_t *dc);
void Item_SetTextExtents(itemDef_t *item, int *width, int *height, const char *text);
void Item_Text_AutoWrapped_Paint(itemDef_t *item, const char *textPtr, vec_t *color);
void Item_Text_Wrapped_Paint(itemDef_t *item, const char *textPtr, vec_t *color);
void Item_ListBox_Paint(displayContextDef_t *dc, itemDef_t *item);
void Script_SetItemColor(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Window_Paint(displayContextDef_t *dc, float (*w_param)[4][32], float fadeAmount, float fadeInAmount, float fadeClamp, float fadeCycle);
void Menu_Setup(displayContextDef_t *dc);
void Menus_CloseByName(displayContextDef_t *dc, const char *p);
void Menu_SetFeederSelection(displayContextDef_t *dc, menuDef_t *menu, int feeder, int index, const char *name);
void Script_Exec(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Menu_TransitionItemByName(menuDef_t *menu, const char *p, rectDef_t rectFrom, rectDef_t rectTo, int time, float amt);
void Script_Transition(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Menu_OrbitItemByName(menuDef_t *menu, const char *p, float x, float y, float cx, float cy, int time);
void Script_Orbit(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_CloseForGameType(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_Close(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_InGameClose(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Menus_Open(displayContextDef_t *dc, menuDef_t *menu);
qboolean Menus_OpenByName(displayContextDef_t *dc, const char *p);
void Script_Open(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_OpenForGameType(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_InGameOpen(displayContextDef_t *dc, itemDef_t *item, const char **args);
qboolean Display_MouseMove(displayContextDef_t *dc, void *p, int x, int y);
itemDef_t *Menu_SetNextCursorItem(displayContextDef_t *dc, menuDef_t *menu);
itemDef_t *Menu_SetPrevCursorItem(displayContextDef_t *dc, menuDef_t *menu);
void Item_TextColor(displayContextDef_t *dc, itemDef_t *item, vec4_t *newColor);
void Item_Text_Paint(displayContextDef_t *dc, itemDef_t *item);
void Item_TextField_Paint(displayContextDef_t *dc, itemDef_t *item);
void Item_YesNo_Paint(displayContextDef_t *dc, itemDef_t *item);
void Item_Slider_Paint(displayContextDef_t *dc, itemDef_t *item);
void Item_Bind_Paint(displayContextDef_t *dc, itemDef_t *item);
void Item_OwnerDraw_Paint(displayContextDef_t *dc, itemDef_t *item);
qboolean Item_Slider_HandleKey(displayContextDef_t *dc, itemDef_t *item, int key, qboolean down);
qboolean Item_YesNo_HandleKey(displayContextDef_t *dc, itemDef_t *item, int key);
qboolean Item_SetFocus(displayContextDef_t *dc, itemDef_t *item, float x, float y);
void Script_SetFocusByDvar(displayContextDef_t *dc, itemDef_t *item, const char **args);
void Script_SetFocus(displayContextDef_t *dc, itemDef_t *item, const char **args);
int Item_ListBox_OverLB(itemDef_t *item, float x, float y);
qboolean Item_ListBox_HandleKey(displayContextDef_t *dc, itemDef_t *item, int key, qboolean down, qboolean force);
qboolean Item_Bind_HandleKey(displayContextDef_t *dc, itemDef_t *item, int key, qboolean down);
qboolean Item_HandleKey(displayContextDef_t *dc, itemDef_t *item, int key, qboolean down);
void Item_ListBox_MouseEnter(itemDef_t *item, float x, float y);
void Item_MouseEnter(displayContextDef_t *dc, itemDef_t *item, float x, float y);
qboolean Menu_HandleMouseMove(displayContextDef_t *dc, menuDef_t *menu, float x, float y);
qboolean Item_TextField_HandleKey(displayContextDef_t *dc, itemDef_t *item, int key);
void Menu_HandleKey(displayContextDef_t *dc, menuDef_t *menu, int key, qboolean down);
void Item_Paint(displayContextDef_t *dc, itemDef_t *item);
void Menu_Paint(displayContextDef_t *dc, menuDef_t *menu, qboolean forcePaint);
void Menu_PaintAll(displayContextDef_t *dc);
void Menus_HandleOOBClick(displayContextDef_t *dc, menuDef_t *menu, int key, qboolean down);

void UI_Component_Init(void);

void UI_MapLoadInfo(const char *filename);
void PC_SourceError(int handle, char *format, ...);
qboolean PC_Script_Parse(int handle, const char **out);
void Item_InitControls(const char (*item)[4]);
qboolean MenuParse_onOpen(const char (*item)[4], int handle);
qboolean MenuParse_onClose(const char (*item)[4], int handle);
qboolean MenuParse_onESC(const char (*item)[4], int handle);
qboolean MenuParse_soundLoop(const char (*item)[4], int handle);
void __attribute_regparm__(2) Item_ValidateTypeData(itemDef_t *item, int handle);
qboolean ItemParse_textsavegame(const char (*item)[4], int handle);
qboolean ItemParse_notselectable(const char (*item)[4], int handle);
qboolean ItemParse_noScrollBars(const char (*item)[4], int handle);
qboolean ItemParse_horizontalscroll(const char (*item)[4], int handle);
void ItemParse_doubleClick(const char (*item)[4], int handle);
qboolean ItemParse_onFocus(const char (*item)[4], int handle);
qboolean ItemParse_leaveFocus(const char (*item)[4], int handle);
qboolean ItemParse_mouseEnter(const char (*item)[4], int handle);
qboolean ItemParse_mouseExit(const char (*item)[4], int handle);
qboolean ItemParse_mouseEnterText(const char (*item)[4], int handle);
qboolean ItemParse_mouseExitText(const char (*item)[4], int handle);
qboolean ItemParse_action(itemDef_t *item, int handle);
qboolean ItemParse_accept(itemDef_t *item, int handle);
qboolean Item_Parse_maxCharsGotoNext(const char (*item)[4], int handle);
qboolean ItemParse_dvarStrList(const char (*item)[4], int handle);
qboolean ItemParse_enableDvar(const char (*item)[4], int handle);
qboolean ItemParse_disableDvar(const char (*item)[4], int handle);
qboolean ItemParse_showDvar(const char (*item)[4], int handle);
qboolean ItemParse_hideDvar(const char (*item)[4], int handle);
qboolean ItemParse_focusDvar(const char (*item)[4], int handle);
void Menu_PostParse(menuDef_t *menu);
qboolean MenuParse_popup(const char (*item)[4], int handle);
qboolean MenuParse_outOfBounds(const char (*item)[4], int handle);
qboolean MenuParse_legacySplitScreenScale(const char (*item)[4], int handle);
qboolean ItemParse_decoration(const char (*item)[4], int handle);
qboolean ItemParse_wrapped(const char (*item)[4], int handle);
qboolean ItemParse_autowrapped(const char (*item)[4], int handle);
qboolean MenuParse_execKey(const char (*item)[4], int handle);
qboolean ItemParse_execKey(const char (*item)[4], int handle);
qboolean ItemParse_textfile(const char (*item)[4], int handle);
qboolean Item_Parse(int handle, const char (*item)[4]);
qboolean MenuParse_itemDef(const char (*item)[4], int handle);
void Item_SetupKeywordHash(void);
void Menu_SetupKeywordHash(void);
qboolean MenuParse_name(menuDef_t *menu, int handle);
qboolean MenuParse_background(const char (*item)[4], int handle);
qboolean MenuParse_cinematic(menuDef_t *menu, int handle);
qboolean ItemParse_name(itemDef_t *item, int handle);
qboolean ItemParse_focusSound(const char (*item)[4], int handle);
qboolean ItemParse_text(itemDef_t *item, int handle);
qboolean ItemParse_group(itemDef_t *item, int handle);
qboolean ItemParse_background(const char (*item)[4], int handle);
qboolean ItemParse_cinematic(itemDef_t *item, int handle);
qboolean ItemParse_dvarTest(itemDef_t *item, int handle);
qboolean ItemParse_dvar(const char (*item)[4], int handle);
qboolean ItemParse_dvarEnumList(const char (*item)[4], int handle);
qboolean ItemParse_outlinecolor(const char (*item)[4], int handle);
qboolean MenuParse_outlinecolor(const char (*item)[4], int handle);
qboolean PC_Rect_Parse(int handle, rectDef_t *r);
qboolean ItemParse_rect(const char (*item)[4], int handle);
qboolean MenuParse_rect(const char (*item)[4], int handle);
qboolean MenuParse_borderSize(const char (*item)[4], int handle);
qboolean MenuParse_backcolor(const char (*item)[4], int handle);
qboolean MenuParse_forecolor(const char (*item)[4], int handle);
qboolean MenuParse_bordercolor(const char (*item)[4], int handle);
qboolean MenuParse_focuscolor(const char (*item)[4], int handle);
qboolean MenuParse_disablecolor(const char (*item)[4], int handle);
qboolean MenuParse_fadeClamp(const char (*item)[4], int handle);
qboolean MenuParse_fadeAmount(const char (*item)[4], int handle);
qboolean MenuParse_fadeInAmount(const char (*item)[4], int handle);
qboolean MenuParse_blurWorld(const char (*item)[4], int handle);
qboolean ItemParse_elementwidth(const char (*item)[4], int handle);
qboolean ItemParse_elementheight(const char (*item)[4], int handle);
qboolean ItemParse_feeder(const char (*item)[4], int handle);
qboolean ItemParse_bordersize(const char (*item)[4], int handle);
qboolean ItemParse_textalignx(const char (*item)[4], int handle);
qboolean ItemParse_textaligny(const char (*item)[4], int handle);
qboolean ItemParse_textscale(const char (*item)[4], int handle);
qboolean ItemParse_backcolor(const char (*item)[4], int handle);
qboolean ItemParse_forecolor(const char (*item)[4], int handle);
qboolean ItemParse_bordercolor(const char (*item)[4], int handle);
qboolean ItemParse_special(const char (*item)[4], int handle);
qboolean ItemParse_dvarFloat(const char (*item)[4], int handle);
qboolean ItemParse_dvarFloatList(const char (*item)[4], int handle);
qboolean MenuParse_fullscreen(const char (*item)[4], int handle);
qboolean MenuParse_style(const char (*item)[4], int handle);
qboolean MenuParse_visible(const char (*item)[4], int handle);
qboolean MenuParse_border(const char (*item)[4], int handle);
qboolean MenuParse_ownerdrawFlag(const char (*item)[4], int handle);
qboolean MenuParse_ownerdraw(const char (*item)[4], int handle);
qboolean MenuParse_fadeCycle(const char (*item)[4], int handle);
qboolean MenuParse_execKeyInt(const char (*item)[4], int handle);
qboolean ItemParse_origin(const char (*item)[4], int handle);
qboolean ItemParse_style(const char (*item)[4], int handle);
qboolean ItemParse_type(const char (*item)[4], int handle);
qboolean ItemParse_elementtype(const char (*item)[4], int handle);
qboolean ItemParse_columns(const char (*item)[4], int handle);
qboolean ItemParse_border(const char (*item)[4], int handle);
qboolean ItemParse_visible(const char (*item)[4], int handle);
qboolean ItemParse_ownerdraw(const char (*item)[4], int handle);
qboolean ItemParse_align(const char (*item)[4], int handle);
qboolean ItemParse_textalign(const char (*item)[4], int handle);
qboolean ItemParse_textstyle(const char (*item)[4], int handle);
qboolean ItemParse_textfont(const char (*item)[4], int handle);
qboolean ItemParse_maxChars(const char (*item)[4], int handle);
qboolean ItemParse_maxPaintChars(const char (*item)[4], int handle);
qboolean ItemParse_ownerdrawFlag(const char (*item)[4], int handle);
qboolean ItemParse_execKeyInt(const char (*item)[4], int handle);
MenuList *UI_LoadMenus(const char *menuFile, int imageTrack);
MenuList *UI_LoadMenu(const char *menuFile, int imageTrack);

void Window_SetStaticFlags(Window *w, const int flags);
qboolean Item_EnableShowViaDvar(const itemDef_t *item, int flag);
qboolean Item_IsEditFieldDef(itemDef_t *item);
listBoxDef_t *Item_GetListBoxDef(itemDef_t *item);
multiDef_t *Item_GetMultiDef(itemDef_t *item);
void *UI_Alloc(int size, int alignment);
void String_Init(void);
qboolean Int_Parse(const char **p, int *i);
qboolean Float_Parse(const char **p, float *f);
void Window_SetOffsetTime(Window *w, int offsetTime);
void Window_SetRect(Window *w, const UiRectangle *rect);
void Window_SetRectClient(Window *w, const UiRectangle *rectClient);
void Window_SetRectEffects0(Window *w, const UiRectangle *rectEffects0);
void Window_SetRectEffects1(Window *w, const UiRectangle *rectEffects1);
void Window_SetDynamicFlags(Window *w, const int flags);
void Menu_SetCursorItem(menuDef_t *menu, int cursorItem);
void Item_SetTextRect(itemDef_t *item, const rectDef_t *textRect);
void Item_SetCursorPos(itemDef_t *item, int cursorPos);
int Item_GetCursorPosOffset(const itemDef_t *item, const char *text, int delta);
void ListBox_SetCursorPos(listBoxDef_t *listBox, int cursorPos);
void ListBox_SetStartPos(listBoxDef_t *listBox, int startPos);
void ListBox_SetEndPos(listBoxDef_t *listBox, int endPos);
Bool ListBox_HasValidCursorPos(const listBoxDef_t *listBox);
void Window_AddDynamicFlags(Window *w, const int newFlags);
void Window_RemoveDynamicFlags(Window *w, const int newFlags);
editFieldDef_t *Item_GetEditFieldDef(itemDef_t *item);
const char *String_Alloc(const char *p);
void Item_SetScreenCoords(itemDef_t *item, float x, float y, int horzAlign, int vertAlign);
void Menu_UpdatePosition(menuDef_t *menu);
qboolean Rect_Parse(const char **p, rectDef_t *r);

#endif
