#ifndef CLEAN_PC_GAME_MP_G_FUNCS_H
#define CLEAN_PC_GAME_MP_G_FUNCS_H

#include "common_types.h"

void ClientImpacts(gentity_t *ent, pmove_t *pm);
qboolean G_ClientCanSpectateTeam(gclient_t *client, team_t team);
qboolean ClientInactivityTimer(gclient_t *client);
void G_SetLastServerTime(int clientNum, int lastServerTime);
void G_SetClientContents(gentity_t *pEnt);
qboolean GetFollowPlayerState(int clientNum, playerState_t *ps);
void G_PlayerController(gentity_t *self, int *partBits);
void G_PlayerEvent(int clientNum, int event);
void SpectatorThink(gentity_t *ent, usercmd_t *ucmd);
void SpectatorClientEndFrame(gentity_t *ent);
void G_TouchTriggers(gentity_t *ent);
void ClientEvents(gentity_t *ent, int oldEventSequence);
void P_DamageFeedback(gentity_t *player);
qboolean StuckInClient(gentity_t *self);
void ClientThink_real(gentity_t *ent, usercmd_t *ucmd);
void G_RunClient(gentity_t *ent);
void ClientThink(int clientNum);
void ClientEndFrame(gentity_t *ent);

void GScr_AddFieldsForClient(void);
void Scr_SetClientField(gclient_t *client, int offset);
void Scr_GetClientField(gclient_t *client, int offset);

void G_GetPlayerViewDirection(const gentity_t *ent, vec_t *forward, vec_t *right, vec_t *up);
void ClientBegin(int clientNum);
void ClientDisconnect(int clientNum);
int G_GetNonPVSFriendlyInfo(gentity_t *pSelf, vec_t *vPosition, int iLastUpdateEnt);
void G_BroadcastVoice(gentity_t *talker, VoicePacket_t *voicePacket);
void SetClientViewAngle(gentity_t *ent, const vec_t *angle);
void ClientSpawn(gentity_t *ent, const vec_t *spawn_origin, const vec_t *spawn_angles);
void G_GetPlayerViewOrigin(const gentity_t *ent, vec_t *origin);
void ClientUserinfoChanged(int clientNum);
char *ClientConnect(int clientNum, int scriptPersId);

void PlayerCmd_takeWeapon(struct scr_entref_t entref);
void PlayerCmd_takeAllWeapons(scr_entref_t entref);
void PlayerCmd_setAngles(scr_entref_t entref);
void PlayerCmd_getAngles(scr_entref_t entref);
void PlayerCmd_useButtonPressed(scr_entref_t entref);
void PlayerCmd_attackButtonPressed(scr_entref_t entref);
void PlayerCmd_meleeButtonPressed(scr_entref_t entref);
void PlayerCmd_playerADS(scr_entref_t entref);
void PlayerCmd_isOnGround(scr_entref_t entref);
void PlayerCmd_pingPlayer(scr_entref_t entref);
void PlayerCmd_SetViewmodel(scr_entref_t entref);
void PlayerCmd_GetViewmodel(scr_entref_t entref);
void PlayerCmd_showScoreboard(scr_entref_t entref);
void PlayerCmd_setSpawnWeapon(scr_entref_t entref);
void PlayerCmd_dropItem(scr_entref_t entref);
void PlayerCmd_Suicide(scr_entref_t entref);
void PlayerCmd_OpenMenu(scr_entref_t entref);
void PlayerCmd_OpenMenuNoMouse(scr_entref_t entref);
void PlayerCmd_CloseMenu(scr_entref_t entref);
void PlayerCmd_CloseInGameMenu(scr_entref_t entref);
void PlayerCmd_SetWeaponSlotWeapon(scr_entref_t entref);
void PlayerCmd_SetWeaponSlotAmmo(scr_entref_t entref);
void PlayerCmd_GetWeaponSlotClipAmmo(scr_entref_t entref);
void PlayerCmd_SetWeaponSlotClipAmmo(scr_entref_t entref);
void PlayerCmd_SetWeaponClipAmmo(scr_entref_t entref);
void iclientprintln(scr_entref_t entref);
void iclientprintlnbold(scr_entref_t entref);
void PlayerCmd_spawn(scr_entref_t entref);
void PlayerCmd_setEnterTime(scr_entref_t entref);
void BodyEnd(gentity_t *ent);
void PlayerCmd_SetClientDvar(scr_entref_t entref);
void PlayerCmd_IsTalking(scr_entref_t entref);
void PlayerCmd_FreezeControls(scr_entref_t entref);
void PlayerCmd_DisableWeapon(scr_entref_t entref);
void PlayerCmd_EnableWeapon(scr_entref_t entref);
void PlayerCmd_SetReverb(scr_entref_t entref);
void PlayerCmd_DeactivateReverb(scr_entref_t entref);
void PlayerCmd_SetChannelVolumes(scr_entref_t entref);
void PlayerCmd_DeactivateChannelVolumes(scr_entref_t entref);
void ScrCmd_IsLookingAt(scr_entref_t entref);
void ScrCmd_PlayLocalSound(scr_entref_t entref);
void PlayerCmd_SayAll(scr_entref_t entref);
void PlayerCmd_SayTeam(scr_entref_t entref);
void PlayerCmd_AllowSpectateTeam(scr_entref_t entref);
void PlayerCmd_GetGuid(scr_entref_t entref);
void PlayerCmd_giveWeapon(scr_entref_t entref);
void PlayerCmd_hasWeapon(scr_entref_t entref);
void PlayerCmd_switchToWeapon(scr_entref_t entref);
void PlayerCmd_switchToOffhand(scr_entref_t entref);
void PlayerCmd_giveStartAmmo(scr_entref_t entref);
void PlayerCmd_giveMaxAmmo(scr_entref_t entref);
void PlayerCmd_getFractionStartAmmo(scr_entref_t entref);
void PlayerCmd_getFractionMaxAmmo(scr_entref_t entref);
void PlayerCmd_setOrigin(scr_entref_t entref);
void PlayerCmd_finishPlayerDamage(scr_entref_t entref);
void PlayerCmd_ClonePlayer(scr_entref_t entref);
void PlayerCmd_getCurrentWeapon(scr_entref_t entref);
void PlayerCmd_getCurrentOffhand(scr_entref_t entref);
void PlayerCmd_GetWeaponSlotWeapon(scr_entref_t entref);
void PlayerCmd_GetWeaponSlotAmmo(scr_entref_t entref);
BuiltinMethod Player_GetMethod(const char **pName);

void DeathmatchScoreboardMessage(gentity_t *ent);
void Cmd_Score_f(gentity_t *ent);
qboolean CheatsOk(gentity_t *ent);
char *ConcatArgs(int start);
void G_setfog(const char *fogstring);
qboolean Cmd_FollowCycle_f(gentity_t *ent, int dir);
qboolean G_IsPlaying(gentity_t *ent);
void Cmd_CallVote_f(gentity_t *ent);
void Cmd_Vote_f(gentity_t *ent);
void Cmd_SetViewpos_f(gentity_t *ent);
void Cmd_MenuResponse_f(gentity_t *pEnt);
void G_Say(gentity_t *ent, gentity_t *target, int mode, const char *chatText);
void Cmd_GameCommand_f(gentity_t *ent);
void StopFollowing(gentity_t *ent);
void Cmd_Give_f(gentity_t *ent);
void Cmd_Take_f(gentity_t *ent);
void ClientCommand(int clientNum);

void G_ParseHitLocDmgTable(void);
int G_IndexForMeansOfDeath(const char *pszMOD);
scr_string_t G_GetHitLocationString(hitLocation_t hitLoc);
hitLocation_t G_GetHitLocationIndexFromString(int sString);
float CanDamage(gentity_t *targ, const vec_t *origin);
void G_Damage(gentity_t *targ, gentity_t *inflictor, gentity_t *attacker, const vec_t *dir, const vec_t *point, int damage, int dflags, int mod, hitLocation_t hitLoc, int timeOffset);
qboolean G_RadiusDamage(const vec_t *origin, gentity_t *inflictor, gentity_t *attacker, float fInnerDamage, float fOuterDamage, float radius, gentity_t *ignore, int mod);
void player_die(gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage, int meansOfDeath, int iWeapon, const vec_t *vDir, const hitLocation_t hitLoc, int psTimeOffset);

void Scr_GetHudElemField(int entnum, int offset);
void Scr_SetHudElemField(int entnum, int offset);
void Scr_FreeHudElemConstStrings(game_hudelem_t *hud);
void GScr_AddFieldsForHudElems(void);
BuiltinMethod HudElem_GetMethod(const char **pName);
void HudElem_UpdateClient(gclient_t *client, int clientNum, hudelem_update_t which);
void HudElem_GetFont(game_hudelem_t *hud, int offset);
void HudElem_GetAlignX(game_hudelem_t *hud, int offset);
void HudElem_GetAlignY(game_hudelem_t *hud, int offset);
void HudElem_GetHorzAlign(game_hudelem_t *hud, int offset);
void HudElem_ClientDisconnect(gentity_t *ent);
void HudElem_DestroyAll(void);
void HECmd_SetTenthsTimerUp(scr_entref_t entref);
void HECmd_SetTenthsTimer(scr_entref_t entref);
void HECmd_SetTimerUp(scr_entref_t entref);
void HECmd_SetTimer(scr_entref_t entref);
void HECmd_SetClockUp(scr_entref_t entref);
void HECmd_SetClock(scr_entref_t entref);
void HECmd_SetValue(scr_entref_t entref);
void HECmd_SetWaypoint(scr_entref_t entref);
void GScr_NewHudElem(void);
void GScr_NewClientHudElem(void);
void GScr_NewTeamHudElem(void);

void DroppedItemClearOwner(gentity_t *pSelf);
void G_GetItemClassname(const gitem_t *item, scr_string_t *out);
void ClearRegisteredItems(void);
void SaveRegisteredWeapons(void);
void SaveRegisteredItems(void);
void RegisterItem(int iItemIndex, qboolean bUpdateCS);
void G_RegisterWeapon(int weapIndex);
qboolean IsItemRegistered(int iItemIndex);
void FinishSpawningItem(gentity_t *ent);
void G_RunCorpseMove(gentity_t *ent);
void G_RunCorpse(gentity_t *ent);
void G_RunItem(gentity_t *ent);
gentity_t *Drop_Item(gentity_t *ent, const gitem_t *item, float angle, qboolean novelocity);
gentity_t *Drop_Weapon(gentity_t *pEnt, int iWeaponIndex, unsigned int tag);
void Touch_Item(gentity_t *ent, gentity_t *other, qboolean bTouched);
void Touch_Item_Auto(gentity_t *ent, gentity_t *other, qboolean bTouched);
void G_SpawnItem(gentity_t *ent, const gitem_t *item);
int Add_Ammo(gentity_t *ent, int weapon, int count, qboolean fillClip);

void G_InitDbgPrint(const char *fmt, void *ptr);
int G_GetSavePersist(void);
void G_SetSavePersist(qboolean savepersist);
float G_GetFogOpaqueDistSqrd(void);
int G_GetClientScore(int clientNum);
int G_GetClientArchiveTime(int clientNum);
void G_SetClientArchiveTime(int clientNum, int time);
clientState_t *G_GetClientState(int clientNum);
int *Hunk_AllocXAnimServer(int size);
void CalculateRanks(void);
void G_LogPrintf(const char *fmt, ...);
void ExitLevel(void);
void DBG_PrintFreeVars(const char *label);
void G_InitGame(int levelTime, int randomSeed, qboolean restart, qboolean savepersist);
void G_RegisterDvars(void);
void CheckVote(void);
int G_RunThink(gentity_t *ent);
void G_TraceCapsule(trace_t *results, const vec_t *start, const vec_t *mins, const vec_t *maxs, const vec_t *end, int passEntityNum, int contentmask);
qboolean G_TraceCapsuleComplete(const vec_t *start, const vec_t *mins, const vec_t *maxs, const vec_t *end, int passEntityNum, int contentmask);
void G_LocationalTrace(trace_t *results, const vec_t *start, const vec_t *end, int passEntityNum, int contentmask, unsigned char *priorityMap);
qboolean G_LocationalTracePassed(const vec_t *start, const vec_t *end, int passEntityNum, int contentmask);
int G_SightTrace(int *hitNum, const vec_t *start, const vec_t *end, int passEntityNum, int contentmask);
void G_AddDebugString(const vec_t *xyz, const vec_t *color, float scale, const char *pszText);
void G_ShutdownGame(qboolean freeScripts);
int G_RunFrame(int levelTime);

void SP_info_null(gentity_t *self);
void SP_info_notnull(gentity_t *self);
void SP_light(gentity_t *self);
void SP_misc_model(gentity_t *ent);
void SP_corona(gentity_t *ent);
void G_InitTurrets(void);
void turret_think(gentity_t *self);
void turret_controller(gentity_t *self, int *partBits);
void TeleportPlayer(gentity_t *player, vec_t *origin, vec_t *angles);
void G_ClientStopUsingTurret(gentity_t *self);
void G_FreeTurret(gentity_t *self);
void turret_think_init(gentity_t *self);
qboolean G_IsTurretUsable(gentity_t *self, gentity_t *owner);
void turret_use(gentity_t *self, gentity_t *owner, gentity_t *activator);
void G_SpawnTurret(gentity_t *self, const char *weaponinfoname);
void SP_turret(gentity_t *self);
void turret_think_client(gentity_t *self);

void G_ExplodeMissile(gentity_t *ent);
gentity_t *fire_grenade(gentity_t *self, vec_t *start, vec_t *dir, int grenadeWPID, int time);
gentity_t *fire_rocket(gentity_t *self, vec_t *start, vec_t *dir);
void G_RunMissile(gentity_t *ent);

void use_trigger_use(gentity_t *ent, gentity_t *other, gentity_t *activator);
void trigger_use(gentity_t *ent);
void trigger_use_touch(gentity_t *ent);
qboolean G_TryPushingEntity(gentity_t *check, gentity_t *pusher, vec_t *move, vec_t *amove);
void G_MoverTeam(gentity_t *ent);
void G_RunMover(gentity_t *ent);

unsigned int GScr_AllocString(const char *s);
void Scr_LoadLevel(void);
void GScr_FreeScripts(void);
void ScrCmd_GetClanId(struct scr_entref_t entref);
void ScrCmd_GetClanName(scr_entref_t entref);
void ScrCmd_GetClanMotto(scr_entref_t entref);
void ScrCmd_GetClanDescription(scr_entref_t entref);
void ScrCmd_GetClanURL(scr_entref_t entref);
void print(void);
void assertCmd(void);
void assertexCmd(void);
void assertmsgCmd(void);
void GScr_IsDefined(void);
void GScr_IsString(void);
void GScr_IsAlive(void);
void GScr_GetDvar(void);
void GScr_GetDvarInt(void);
void GScr_GetDvarFloat(void);
void GScr_GetTime(void);
void Scr_GetEntByNum(void);
void Scr_GetWeaponModel(void);
void GScr_GetAnimLength(void);
void GScr_AnimHasNotetrack(void);
void GScr_PrecacheTurret(void);
void ScrCmd_SoundExists(void);
void ScrCmd_PlayRumble(scr_entref_t entref);
void ScrCmd_PlayLoopRumble(scr_entref_t entref);
void ScrCmd_StopRumble(scr_entref_t entref);
qboolean G_GetHintStringIndex(int *piIndex, const char *pszString);
unsigned int __attribute_regparm__(2) SetObjectiveIcon(objective_t *obj, int paramNum);
void Scr_Objective_Icon(void);
void Scr_Objective_OnEntity(void);
void Scr_Objective_Current(void);
void GScr_Objective_Team(void);
void GScr_LogPrint(void);
void GScr_WorldEntNumber(void);
void GScr_Obituary(void);
void GScr_getStartTime(void);
void GScr_PrecacheMenu(void);
int GScr_GetScriptMenuIndex(const char *pszMenu);
void GScr_PrecacheStatusIcon(void);
int GScr_GetStatusIconIndex(const char *pszIcon);
void GScr_PrecacheHeadIcon(void);
int GScr_GetHeadIconIndex(const char *pszIcon);
void Scr_BulletTracePassed(void);
void Scr_SightTracePassed(void);
void Scr_PhysicsTrace(void);
void Scr_RandomInt(void);
void Scr_RandomFloat(void);
void Scr_RandomIntRange(void);
void Scr_RandomFloatRange(void);
void GScr_sin(void);
void GScr_cos(void);
void GScr_tan(void);
void GScr_asin(void);
void GScr_acos(void);
void GScr_atan(void);
void GScr_CastInt(void);
void Scr_Distance(void);
void Scr_DistanceSquared(void);
void Scr_LengthSquared(void);
void Scr_Closer(void);
void Scr_VectorDot(void);
void Scr_VectorToAngles(void);
void Scr_AnglesToUp(void);
void Scr_AnglesToRight(void);
void Scr_AnglesToForward(void);
void Scr_IsSubStr(void);
void Scr_GetSubStr(void);
void Scr_ToLower(void);
void Scr_StrTok(void);
void Scr_MusicPlay(void);
void Scr_SoundFade(void);
void Scr_PrecacheModel(void);
void Scr_PrecacheShellShock(void);
void Scr_PrecacheItem(void);
void Scr_PrecacheShader(void);
void Scr_PrecacheString(void);
void Scr_PrecacheRumble(void);
void GScr_RadiusDamage(void);
void GScr_SetPlayerIgnoreRadiusDamage(void);
void GScr_GetMoveDelta(void);
void GScr_GetAngleDelta(void);
void GScr_GetNorthYaw(void);
void Scr_LoadFX(void);
void Scr_PlayFXOnTag(void);
void Scr_SetFog(const char *cmd, float fNear, float fFar, float fDensity, float fRed, float fGreen, float fBlue, float fTime);
void Scr_SetLinearFog(void);
void Scr_SetExponentialFog(void);
void GScr_IsPlayer(void);
void GScr_IsPlayerNumber(void);
void GScr_SetWinningPlayer(void);
void GScr_SetWinningTeam(void);
void GScr_GetTeamScore(void);
void GScr_SetTeamScore(void);
void GScr_SetClientNameMode(void);
void GScr_UpdateClientNames(void);
void GScr_GetTeamPlayersAlive(void);
void GScr_GetNumParts(void);
void GScr_GetPartName(void);
void GScr_Earthquake(void);
void GScr_MapRestart(void);
void GScr_LoadMap(void);
void GScr_ExitLevel(void);
void GScr_AddTestClient(void);
void GScr_AllClientsPrint(void);
void GScr_MapExists(void);
void GScr_SetVoteString(void);
void GScr_SetVoteTime(void);
void GScr_SetVoteYesCount(void);
void GScr_SetVoteNoCount(void);
void GScr_KickPlayer(void);
void GScr_BanPlayer(void);
void GScr_ClientPrint(void);
void GScr_OpenFile(void);
void GScr_CloseFile(void);
void GScr_FPrintln(void);
void GScr_FReadLn(void);
void GScr_FGetArg(void);
void GScr_SetArchive(void);
void Scr_PlayRumbleOnPos(void);
void Scr_PlayLoopRumbleOnPos(void);
void Scr_StopAllRumbles(void);
void Scr_IsSplitscreen(void);
void GScr_MatchEnd(void);
void GScr_SetPlayerTeamRank(void);
void GScr_SendXboxLiveRanks(void);
void GScr_EndXboxLiveLobby(void);
void GScr_ReleaseClaimedTrigger(scr_entref_t entref);
BuiltinFunction Scr_GetFunction(const char **pName, int *type);
BuiltinMethod Scr_GetMethod(const char **pName, int *type);
void Scr_SetOrigin(gentity_t *ent, int offset);
void Scr_SetAngles(gentity_t *ent, int offset);
void Scr_SetHealth(gentity_t *ent, int offset);
void GScr_AddEntity(gentity_t *pEnt);
void Scr_ParseGameTypeList(void);
const char *Scr_GetGameTypeNameForScript(const char *pszGameTypeScript);
void Scr_LoadGameType(void);
void Scr_StartupGameType(void);
void Scr_PlayerConnect(gentity_t *self);
void Scr_PlayerDisconnect(gentity_t *self);
void Scr_VoteCalled(gentity_t *self, char *command, char *param1, char *param2);
void Scr_PlayerVote(gentity_t *self, char *option);
void GScr_print3d(void);
void GScr_line(void);
void GScr_Spawn(void);
void GScr_SpawnTurret(void);
void Scr_VectorNormalize(void);
void Scr_GrenadeExplosionEffect(void);
void Scr_Objective_Position(void);
void GScr_positionWouldTelefrag(void);
void GScr_GetBrushModelCenter(void);
void Scr_Objective_Delete(void);
void G_InitObjectives(void);
void Scr_BulletTrace(void);
void Scr_Objective_Add(void);
void Scr_Objective_State(void);
void Scr_MusicStop(void);
void Scr_AmbientPlay(void);
void Scr_AmbientStop(void);
void Scr_PlayLoopedFX(void);
unsigned int Scr_ConstructMessageString(int firstParmIndex, int lastParmIndex, const char *errorContext, char *string, int stringLimit);
void GScr_MakeDvarServerInfo(void);
void GScr_ClientAnnouncement(void);
void GScr_Announcement(void);
void GScr_SetDvar(void);
void Scr_MakeGameMessage(int iClientNum, const char *pszCmd);
void GScr_IsValidGameType(void);
qboolean Scr_IsValidGameType(const char *pszGameType);
void Scr_Length(void);
void println(void);
void Scr_PlayerDamage(gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage, int dflags, int meansOfDeath, int iWeapon, const vec_t *vPoint, const vec_t *vDir, const hitLocation_t hitLoc, int timeOffset);
void Scr_PlayerKilled(gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage, int meansOfDeath, int iWeapon, const vec_t *vDir, const hitLocation_t hitLoc, int psTimeOffset, int deathAnimDuration);
void ScrCmd_Show(scr_entref_t entref);
void ScrCmd_Hide(scr_entref_t entref);
void ScrCmd_ShowToPlayer(scr_entref_t entref);
void GScr_EnableGrenadeTouchDamage(scr_entref_t entref);
void GScr_DisableGrenadeTouchDamage(scr_entref_t entref);
void GScr_EnableGrenadeBounce(scr_entref_t entref);
void GScr_DisableGrenadeBounce(scr_entref_t entref);
void GScr_EnableAimAssist(scr_entref_t entref);
void GScr_DisableAimAssist(scr_entref_t entref);
void ScrCmd_attach(scr_entref_t entref);
void ScrCmd_detach(scr_entref_t entref);
void ScrCmd_detachAll(scr_entref_t entref);
void ScrCmd_GetAttachSize(scr_entref_t entref);
void ScrCmd_GetAttachModelName(scr_entref_t entref);
void ScrCmd_GetAttachTagName(scr_entref_t entref);
void ScrCmd_GetAttachIgnoreCollision(scr_entref_t entref);
void ScrCmd_LinkTo(scr_entref_t entref);
void ScrCmd_Unlink(scr_entref_t entref);
void ScrCmd_EnableLinkTo(scr_entref_t entref);
void ScrCmd_GetOrigin(scr_entref_t entref);
void ScrCmd_GetEye(scr_entref_t entref);
void ScrCmd_UseBy(scr_entref_t entref);
void Scr_SetStableMissile(scr_entref_t entref);
void ScrCmd_IsTouching(scr_entref_t entref);
void ScrCmd_PlaySound(scr_entref_t entref);
void ScrCmd_PlaySoundAsMaster(scr_entref_t entref);
void ScrCmd_PlayLoopSound(scr_entref_t entref);
void ScrCmd_StopLoopSound(scr_entref_t entref);
void ScrCmd_Delete(scr_entref_t entref);
void ScrCmd_SetModel(scr_entref_t entref);
void ScrCmd_GetNormalHealth(scr_entref_t entref);
void ScrCmd_SetNormalHealth(scr_entref_t entref);
void ScrCmd_SetContents(scr_entref_t entref);
void GScr_SetCursorHint(scr_entref_t entref);
void GScr_SetHintString(scr_entref_t entref);
void GScr_ViewKick(scr_entref_t entref);
void GScr_StopShellShock(scr_entref_t entref);
void GScr_ShellShock(scr_entref_t entref);
void GScr_GetAmmoCount(scr_entref_t entref);
void GScr_LocalToWorldCoords(scr_entref_t entref);
void GScr_SetRightArc(scr_entref_t entref);
void GScr_SetLeftArc(scr_entref_t entref);
void GScr_SetTopArc(scr_entref_t entref);
void GScr_SetBottomArc(scr_entref_t entref);
void GScr_GetEntityNumber(scr_entref_t entref);
void GScr_PlaceSpawnPoint(scr_entref_t entref);
void GScr_UpdateScores(scr_entref_t entref);
void GScr_SetTeamForTrigger(scr_entref_t entref);
void GScr_ClientClaimTrigger(scr_entref_t entref);
void GScr_ClientReleaseTrigger(scr_entref_t entref);
void Scr_PlayFX(void);
void iprintln(void);
void iprintlnbold(void);
void GScr_LoadGameTypeScript(void);
void GScr_LoadScripts(int inst);

void ScriptEntCmdGetCommandTimes(float *pfTotalTime, float *pfAccelTime, float *pfDecelTime);
void ScriptEntCmd_Solid(scr_entref_t entref);
void ScriptEntCmd_NotSolid(scr_entref_t entref);
BuiltinMethod ScriptEnt_GetMethod(const char **pName);
void InitScriptMover(gentity_t *pSelf);
void SP_script_origin(gentity_t *pSelf);
void SP_script_model(gentity_t *pSelf);
void SP_script_brushmodel(gentity_t *pSelf);
void ScriptEntCmd_GravityMove(scr_entref_t entref);
void ScriptEntCmd_RotateVelocity(scr_entref_t entref);
void Reached_ScriptMover(gentity_t *pEnt);
void ScriptEnt_RotateAxis(scr_entref_t entref, int iAxis);
void ScriptEntCmd_RotateRoll(scr_entref_t entref);
void ScriptEntCmd_RotateYaw(scr_entref_t entref);
void ScriptEntCmd_RotatePitch(scr_entref_t entref);
void ScriptEnt_MoveAxis(scr_entref_t entref, int iAxis);
void ScriptEntCmd_MoveZ(scr_entref_t entref);
void ScriptEntCmd_MoveY(scr_entref_t entref);
void ScriptEntCmd_MoveX(scr_entref_t entref);
void ScriptEntCmd_RotateTo(scr_entref_t entref);
void ScriptEntCmd_MoveTo(scr_entref_t entref);

qboolean G_SpawnString(const char *key, const char *defaultString, const char **out);
void G_DuplicateEntityFields(gentity_t *dest, const gentity_t *source);
qboolean G_CallSpawnEntity(gentity_t *ent);
void GScr_AddFieldsForEntity(void);
void GScr_AddFieldsForRadiant(void);
void Scr_AddEntity(gentity_t *ent);
gentity_t *Scr_GetEntity(unsigned int index);
void Scr_FreeHudElem(game_hudelem_t *hud);
void Scr_AddHudElem(game_hudelem_t *hud);
scr_thread_t Scr_ExecEntThread(gentity_t *ent, scr_func_t handle, unsigned int paramcount);
void Scr_Notify(gentity_t *ent, unsigned short stringValue, unsigned int paramcount);
void Scr_GetGenericField(byte *b, fieldtype_t type, int ofs);
void Scr_GetEnt(void);
void Scr_GetEntArray(void);
qboolean G_SpawnFloat(const char *key, const char *defaultString, float *out);
qboolean G_SpawnInt(const char *key, const char *defaultString, int *out);
qboolean G_SpawnVector(const char *key, const char *defaultString, float *out);
void SP_worldspawn(void);
void G_LoadStructs(void);
void Scr_SetGenericField(byte *b, fieldtype_t type, int ofs);
qboolean Scr_SetObjectField(unsigned int classnum, int entnum, int offset);
void Scr_GetObjectField(unsigned int classnum, int entnum, int offset);
void Scr_FreeEntity(gentity_t *ent);
void G_CallSpawn(void);
void G_SpawnEntitiesFromString(void);

void Svcmd_RemoveIP_f(void);
void Svcmd_EntityList_f(void);
void G_ProcessIPBans(void);
qboolean ConsoleCommand(void);

qboolean OnSameTeam(gentity_t *ent1, gentity_t *ent2);
void TeamplayInfoMessage(gentity_t *ent);
void CheckTeamStatus(void);

void G_Trigger(gentity_t *self, gentity_t *other);
void hurt_use(gentity_t *self, gentity_t *other, gentity_t *activator);
void SP_trigger_lookat(gentity_t *self);
void SP_trigger_hurt(gentity_t *self);
void SP_trigger_damage(gentity_t *pSelf);
void SP_trigger_multiple(gentity_t *ent);
void SP_trigger_radius(gentity_t *ent);
void SP_trigger_disk(gentity_t *ent);
void SP_trigger_once(gentity_t *ent);
void Touch_Multi(gentity_t *self, gentity_t *other, qboolean bTouched);
void hurt_touch(gentity_t *self, gentity_t *other, qboolean bTouched);
void Activate_trigger_damage(gentity_t *pEnt, gentity_t *pOther, int iDamage, int iMOD);
void G_GrenadeTouchTriggerDamage(gentity_t *pActivator, vec_t *vStart, vec_t *vEnd, int iDamage, int iMOD);
void G_CheckHitTriggerDamage(gentity_t *pActivator, vec_t *vStart, vec_t *vEnd, int iDamage, int iMOD);
void Die_trigger_damage(gentity_t *pSelf, gentity_t *pInflictor, gentity_t *pAttacker, int iDamage, int iMod, int iWeapon, const vec_t *vDir, const hitLocation_t hitLoc, int timeOffset);
void Pain_trigger_damage(gentity_t *pSelf, gentity_t *pAttacker, int iDamage, const vec_t *vPoint, const int iMod, const vec_t *vDir, const hitLocation_t hitLoc);
void Use_trigger_damage(gentity_t *pEnt, gentity_t *pOther, gentity_t *pActivator);

int G_FindConfigstringIndex(const char *name, int start, int max, qboolean create, const char *errormsg);
int G_LocalizedStringIndex(const char *string);
int G_ShaderIndex(const char *name);
int G_ModelIndex(const char *name);
const char *G_ModelName(int index);
int G_TagIndex(const char *name);
int G_EffectIndex(const char *name);
int G_ShellShockIndex(const char *name);
SoundAlias G_SoundAliasIndex(const char *name);
unsigned char G_SetModel(gentity_t *ent, const char *modelName);
void G_SafeDObjFree(gentity_t *ent);
qboolean G_DObjUpdateServerTime(gentity_t *ent, qboolean bNotify);
int G_DObjCalcPose(gentity_t *ent);
int G_DObjCalcBone(gentity_t *ent, int boneIndex);
DObjAnimMat_s *G_DObjGetLocalTagMatrix(gentity_t *ent, unsigned int tagName);
unsigned char G_InitGentity(gentity_t *e);
unsigned char G_PrintEntities(void);
int G_GetPlayerCorpseIndex(gentity_t *ent);
void G_FreeEntityDelay(gentity_t *ed);
void G_AddPredictableEvent(gentity_t *ent, int event, int eventParm);
unsigned char G_AddEvent(gentity_t *ent, int event, int eventParm);
unsigned char G_SetConstString(scr_string_t *to, const char *from);
unsigned char G_SetAngle(gentity_t *ent, const vec_t *angle);
qboolean G_XModelBad(int index);
unsigned char G_SetOrigin(gentity_t *ent, const vec_t *origin);
unsigned char G_PlaySoundAlias(gentity_t *ent, int index);
unsigned char G_OverrideModel(int modelindex, const char *defaultModelName);
int G_AnimScriptSound(int client, snd_alias_list_t *aliasList);
unsigned char G_CalcTagParentAxis(gentity_t *ent, vec3_t *parentAxis);
unsigned char G_SetFixedLink(gentity_t *ent, int eAngles);
unsigned char G_CalcTagAxis(gentity_t *ent, qboolean bAnglesOnly);
unsigned char G_EntUnlink(gentity_t *ent);
qboolean G_EntLinkToWithOffset(gentity_t *ent, gentity_t *parent, unsigned int tagName, const vec_t *originOffset, const vec_t *anglesOffset);
qboolean G_EntLinkTo(gentity_t *ent, gentity_t *parent, unsigned int tagName);
void G_GeneralLink(gentity_t *ent);
unsigned char G_FreeEntity(gentity_t *ed);
int G_GetFreePlayerCorpseIndex(void);
void G_DObjUpdate(gentity_t *ent);
unsigned char G_EntDetachAll(gentity_t *ent);
qboolean G_EntDetach(gentity_t *ent, const char *modelName, unsigned int tagName);
qboolean G_EntAttach(gentity_t *ent, const char *modelName, unsigned int tagName, qboolean ignoreCollision);
gentity_t *G_Spawn(void);
gentity_t *G_TempEntity(const vec_t *origin, int event);
gentity_t *G_SpawnPlayerClone(void);
qboolean G_DObjGetWorldTagMatrix(gentity_t *ent, unsigned int tagName, vec3_t *tagMat);
int G_DObjGetWorldTagPos(gentity_t *ent, unsigned int tagName, vec_t *pos);

void SnapVectorTowards(vec_t *v, vec_t *to);
qboolean LogAccuracyHit(gentity_t *target, gentity_t *attacker);
int G_GetWeaponIndexForName(const char *name);
void G_SetEquippedOffHand(int clientNum, int offHandIndex);
void G_SelectWeaponIndex(int clientNum, int iWeaponIndex);
void Weapon_Melee(gentity_s (*ent)[16], weaponParms *wp, float range, float width, float height);
void FireWeaponMelee(gentity_s (*ent)[16]);
void Weapon_RocketLauncher_Fire(gentity_t *ent, float spread, weaponParms *wp);
gentity_t *weapon_grenadelauncher_fire(gentity_t *ent, int grenType, weaponParms *wp);
void G_UseOffHand(gentity_t *ent);
Bool Melee_Trace(gentity_t *ent, weaponParms *wp, int damage, float range, float width, float height, trace_t *trace, vec_t *endPos);
void G_SetupWeaponDef(void);
void Bullet_Endpos(float spread, vec_t *end, const weaponParms *wp, float maxRange);
void Bullet_Fire(gentity_s (*attacker)[16], float spread, weaponParms *wp, gentity_s (*weaponEnt)[16], int gametime);
void FireWeaponAntiLag(gentity_s (*ent)[16], int gametime);
qboolean G_GivePlayerWeapon(playerState_t *pPS, int iWeaponIndex);

void Player_UpdateActivate(gentity_t *ent);
void Player_UpdateCursorHints(gentity_t *ent);
void Player_UpdateLookAtEntity(gentity_t *ent);

void GScr_LoadConsts(void);

#endif
