#ifndef CLEAN_PC_EFFECTSCORE_FX_FUNCS_H
#define CLEAN_PC_EFFECTSCORE_FX_FUNCS_H

#include "common_types.h"

void FxArchive_FxArchive(const FxArchive *_this);
void FxArchive_BeginReading(const FxArchive *_this, MemoryFile *memFile);
void FxArchive_ReadData(const FxArchive *_this, void *p, int byteCount);
void FxArchive_WriteData(const FxArchive *_this, const void *p, int byteCount);
void FxArchive_ArchiveEffect(const FxArchive *_this, const EffectTemplate **fx);
void FxArchive_ArchiveMaterial(const FxArchive *_this, MaterialHandle *ph);
void FxArchive_ArchiveModel(const FxArchive *_this, struct XModel **model);
void FxArchive_ArchiveChannelInstance(const FxArchive *_this, FxChannelInstance *channelInstance);
void FxArchive_ArchiveFxBoltInfo(const FxArchive *_this, FxBoltInfo *bolt);
void FxArchive_ArchiveFxGfxEntity(const FxArchive *_this, FxGfxEntity *entity);

void FxChannel_CreateDefault(FxChannel *createe, int dimensions, float value1, float value2);
void FxChannel_CreateViaMigration(const FxChannelBackwardCompatible *source, int dimensions, float lifetime, int forceUnitScale, FxChannel *target);

void FxCurveIterator_Create(FxCurveIterator *createe, const FxCurve *master);
float FxCurve_Integrate(const FxCurve *curve, float normDuration);

const FxCurve *FxCurve_AllocAndCreateWithKeys(const float *keyArray, int dimensionCount, int keyCount);

int FX_GetBoneIndex(const int entNum, unsigned int bone);
void FX_PlaySimpleEffect(EffectTemplate *fx, const vec_t *org);
void FX_PlayEffect(EffectTemplate *fx, const vec_t *org, const vec_t *fwd);
void FX_PlayEntityEffect(EffectTemplate *fx, const vec_t *org, vec3_t *axis, const FxBoltInfo *bolt);
int FX_InitSystem(int rendererExists);
void FX_FreeSystem(void);
void FX_FreeActive(void);
void FX_AdjustCamera(PrimType (*refdef)[256], float zfar);
void FX_AdjustTime(int time);
void FX_WarpTime(int time);
float FX_GetEffectLength(EffectTemplate *fx);
void Server_SwitchToValidFxScheduler(void);

void FxMem_Init(void);

void FxBoltFrame_Release(const FxBoltFrame *_this);
const orientation_t *FxBoltFrame_GetOrientation(const FxBoltFrame *_this);
void Effect_Die(const Effect *_this);
Bool Effect_Cull(const Effect *_this);
void Effect_Draw(const Effect *_this);
void Effect_SetTimeStartEnd(const Effect *_this, int start, int end);
unsigned char Effect_TypeID(const Effect *_this);
void Effect_FixupArchiveLoad(const Effect *_this, const PrimitiveTemplate *primTemplate);
void FxChannelInstance_Create(const FxChannel *master, FxChannelInstance *createe);
void Particle_CreateChannelInstances(const Particle *_this, const PrimitiveTemplate *primTemp);
void Particle_SetRandomVelocity2Weights(const Particle *_this, float weight1, float weight2, float weight3);
unsigned char Particle_TypeID(const Particle *_this);
unsigned char OrientedParticle_TypeID(const OrientedParticle *_this);
void Cloud_Die(const Cloud *_this);
void Cloud_CreateChannelInstances(const Cloud *_this, const PrimitiveTemplate *primTemp);
unsigned char Cloud_TypeID(const Cloud *_this);
void Line_Die(const Line *_this);
unsigned char Line_TypeID(const Line *_this);
void Tail_CreateChannelInstances(const Tail *_this, const PrimitiveTemplate *primTemp);
unsigned char Tail_TypeID(const Tail *_this);
unsigned char Cylinder_TypeID(const Cylinder *_this);
Bool Emitter_Cull(const Emitter *_this);
unsigned char Emitter_TypeID(const Emitter *_this);
void Light_CreateChannelInstances(const Light *_this, const PrimitiveTemplate *primTemp);
void Light_Draw(const Light *_this);
unsigned char Light_TypeID(const Light *_this);
void Flash_Init(const Flash *_this);
unsigned char Flash_TypeID(const Flash *_this);
void Particle_AddVisibility(const Particle *_this);
void Emitter_Draw(const Emitter *_this);
void Cylinder_Draw(const Cylinder *_this);
void Tail_Draw(const Tail *_this);
void Line_Draw(const Line *_this);
void Cloud_Draw(const Cloud *_this);
void OrientedParticle_Draw(const OrientedParticle *_this);
void Particle_Draw(const Particle *_this);
Bool Effect_Update(const Effect *_this);
Bool Particle_Cull(const Particle *_this);
Bool OrientedParticle_Cull(const OrientedParticle *_this);
Bool Cloud_Cull(const Cloud *_this);
Bool Line_Cull(const Line *_this);
Bool Tail_Cull(const Tail *_this);
Bool Cylinder_Cull(const Cylinder *_this);
Bool Light_Cull(const Light *_this);
void Particle_SetRandomVelocityWeights(const Particle *_this, float weight1, float weight2, float weight3);
float Particle_GetVisibility(const Particle *_this, const vec_t *start, const vec_t *dir, float halfLen);
void Particle_FixupArchiveLoad(const Particle *_this, const PrimitiveTemplate *primTemplate);
void Light_FixupArchiveLoad(const Light *_this, const PrimitiveTemplate *primTemplate);
void Particle_SetAxis(const Particle *_this, vec3_t *ax);
void Flash_Draw(const Flash *_this);
const FxBoltFramePtr FxBoltFrame_Acquire(const FxBoltInfo *bolt);
void Particle_Die(const Particle *_this);
void Tail_CalcNewEndpoint(const Tail *_this, const orientation_t *or_);
void Cloud_FixupArchiveLoad(const Cloud *_this, const PrimitiveTemplate *primTemplate);
void Tail_FixupArchiveLoad(const Tail *_this, const PrimitiveTemplate *primTemplate);
void Light_UpdateRGB(const Light *_this, const Light *_this_1);
void ZN6EffectD1Ev(void *_this);
void FxBoltFramePtr_Archive(const FxBoltFramePtr *_this, FxArchive *arch);
void ZN6EffectD0Ev(void *_this);
void Effect_SetBoltFrame(const Effect *_this, FxBoltFramePtr *boltFrame);
void Particle_UpdateRGB(const Particle *_this);
Bool Flash_Update(const Flash *_this);
void Particle_IntegrateVelocity(const Particle *_this, float normDuration, vec_t *outVector);
void Particle_IntegrateVelocity2(const Particle *_this, float normDuration, vec_t *outVector);
void Particle_IntegrateTotalVelocity(const Particle *_this, int duration, vec_t *outVector);
void Particle_Particle(const Particle *_this);
void ZN8ParticleD1Ev(void *_this);
void ZN8ParticleD0Ev(void *_this);
void Light_Light(const Light *_this);
void ZN5LightD1Ev(void *_this);
void ZN5LightD0Ev(void *_this);
void Tail_InitEndPoint(const Tail *_this);
Bool Light_Update(const Light *_this);
void Particle_CalcVelocityValue(const Particle *_this, float normTime, vec_t *outVector, const orientation_t *or_);
void Particle_CalcVelocity2Value(const Particle *_this, float normTime, vec_t *outVector, const orientation_t *or_);
void Particle_GetTotalVelocity(const Particle *_this, float normTime, vec_t *outVector, const orientation_t *or_);
void Emitter_UpdateEmitFx(const Emitter *_this, vec_t *bindVelocity, const orientation_t *or_);
void Particle_GetTotalVelocityAtTime0(const Particle *_this, vec_t *outVector);
void Particle_ApplyImpact(const Particle *_this, const orientation_t *or_, float normTime, const vec_t *velocity, float traceFraction, const vec_t *traceNormal);
Bool Particle_UpdateOrigin(const Particle *_this, const orientation_t *or_);
Bool Emitter_Update(const Emitter *_this);
void Particle_UpdateAlpha(const Particle *_this);
Bool Cylinder_Update(const Cylinder *_this);
Bool Tail_Update(const Tail *_this);
Bool Line_Update(const Line *_this);
Bool Cloud_Update(const Cloud *_this);
Bool OrientedParticle_Update(const OrientedParticle *_this);
Bool Particle_Update(const Particle *_this, const Particle *_this_1, const Cloud *_this_2);
void Effect_Archive(const Effect *_this, FxArchive *arch);
void Light_Archive(const Light *_this, FxArchive *arch);
void Flash_Archive(const Flash *_this, FxArchive *arch);
void Particle_Archive(const Particle *_this, FxArchive *arch);
void OrientedParticle_Archive(const OrientedParticle *_this, FxArchive *arch);
void Cloud_Archive(const Cloud *_this, FxArchive *arch);
void Line_Archive(const Line *_this, FxArchive *arch);
void Tail_Archive(const Tail *_this, FxArchive *arch);
void Cylinder_Archive(const Cylinder *_this, FxArchive *arch);
void Emitter_Archive(const Emitter *_this, FxArchive *arch);
void ZN8CylinderD0Ev(void *_this);
void ZN8CylinderD1Ev(void *_this);
void Cylinder_Cylinder(const Cylinder *_this);
void OrientedParticle_OrientedParticle(const OrientedParticle *_this);
void ZN16OrientedParticleD1Ev(void *_this);
void ZN16OrientedParticleD0Ev(void *_this);
void Cloud_Cloud(const Cloud *_this);
void ZN5CloudD1Ev(void *_this);
void ZN5CloudD0Ev(void *_this);
void Line_Line(const Line *_this);
void ZN4LineD1Ev(void *_this);
void ZN4LineD0Ev(void *_this);
void Tail_Tail(const Tail *_this);
void ZN4TailD1Ev(void *_this);
void ZN4TailD0Ev(void *_this);
void Emitter_Emitter(const Emitter *_this);
void ZN7EmitterD1Ev(void *_this);
void ZN7EmitterD0Ev(void *_this);
float Effect_GetVisibility(const Effect *_this, const vec_t *start, const vec_t *dir, float halfLen);
void Effect_AddVisibility(const Effect *_this);
Bool Flash_Cull(const Flash *_this);
void ZN5FlashD0Ev(void *_this);
void ZN5FlashD1Ev(void *_this);

void *MediaHandles_GetHandle(const MediaHandles *_this);
void FxScheduler_FxScheduler(const FxScheduler *_this);
float FxScheduler_GetEffectLength(const FxScheduler *_this, EffectTemplate *fx);
void FX_InitTemplates(void);
EffectTemplate *FX_TryRegisterEffect(const char *name);
Bool FX_GetBoltingFrame(const PrimitiveTemplate *primTemp, const FxBoltInfo *bolt, FxBoltFramePtr *boltFrame);
void FxScheduler_CreateEffect(const FxScheduler *_this, const EffectTemplate *fx, const PrimitiveTemplate *primTemp, const FxBoltInfo *bolt, const vec_t *origin, MediaHandles *(*axis)[4], int lateTime, int indexInBatch);
void FxScheduler_PlayEffect(const FxScheduler *_this, const EffectTemplate *fx, const vec_t *origin, MediaHandles *(*axis)[4], const FxBoltInfo *bolt);
void FxScheduler_Clean(const FxScheduler *_this, unsigned char bRemoveTemplates, EffectTemplate *fxToPreserve);
void FxScheduler_GetDecalColor(const FxScheduler *_this, const PrimitiveTemplate *primTemp, vec_t *rgba);
float FxScheduler_GetDecalAlpha(const FxScheduler *_this, const PrimitiveTemplate *primTemp);
float FxScheduler_GetDecalSize(const FxScheduler *_this, const PrimitiveTemplate *primTemp);
EffectTemplate *MediaHandles_GetEffect(const MediaHandles *_this);
void FxScheduler_CreateDecalEffect(const FxScheduler *_this, const PrimitiveTemplate *primTemp, vec_t *org, MediaHandles *(*ax)[4]);
void ScheduledEffect_Archive(const ScheduledEffect *_this, FxArchive *arch);
void FxScheduler_Archive(const FxScheduler *_this, FxArchive *arch);

void FX_CleanTemplate(EffectTemplate *fx);
void FX_CreateDefaultEffect(void);
void MediaHandles_Shutdown(const MediaHandles *_this);
void MediaHandles_AddHandle(const MediaHandles *_this, TMediaElement item);
EffectTemplate *FX_ParseEffect(GenericParser2 *parser, const char *name);
EffectTemplate *FX_RegisterEffect(const char *fileName);
void MediaHandles_AddEffect(const MediaHandles *_this, EffectTemplate *fx);

void FxHelper_FxHelper(const FxHelper *_this);
void FxHelper_Init(const FxHelper *_this);
void FxHelper_AdjustTime(const FxHelper *_this, int intime);
void FxHelper_WarpTime(const FxHelper *_this, int intime);
void FxHelper_Trace(const FxHelper *_this, trace_t *tr, vec_t *start, const vec_t *min, const vec_t *max, vec_t *end, int skipEntNum, int flags);
void FxHelper_AddFxToScene(const FxHelper *_this, GfxEntity *ent, const struct XModel *model);
void FxHelper_SetIgnorePrecacheErrors(const FxHelper *_this, int ignore);
const char *FxHelper_GetMaterialName(const FxHelper *_this, MaterialHandle handle);
int FxHelper_GetMaterialSubimageCount(const FxHelper *_this, MaterialHandle handle);
Bool FxHelper_IsMaterialRefractive(const FxHelper *_this, MaterialHandle handle);
void FxHelper_AddLightToScene(const FxHelper *_this, vec_t *org, float radius, float red, float green, float blue);
void FxHelper_CameraShake(const FxHelper *_this, vec_t *origin, float intensity, int radius, int time_);
int FxHelper_GetSeed(const FxHelper *_this);
Bool FxHelper_CullSphere(const FxHelper *_this, const vec_t *worldPos, float radius, int planeCount);
Bool FxHelper_CullSpherePreviousFrame(const FxHelper *_this, const vec_t *worldPos, float radius);
Bool FxHelper_CullCylinder(const FxHelper *_this, const vec_t *worldPos0, const vec_t *worldPos1, float radius0, float radius1, int planeCount);
void FxHelper_CalcFrustumPlanes(const FxHelper *_this, refdef_t *refdef, float zfar);
void FxHelper_AdjustCamera(const FxHelper *_this, refdef_t *refdef, float zfar);
void FxHelper_Archive(const FxHelper *_this, FxArchive *arch);

Bool PrimitiveTemplate_ParsePrimitive(const PrimitiveTemplate *_this, GPGroup *grp);
void FxRange_SetRange(const FxRange *_this, float min, float max);
void PrimitiveTemplate_Shutdown(const PrimitiveTemplate *_this);
float FxRange_GetValPct(const FxRange *_this, float percent);
Bool PrimitiveTemplate_ParseGroupFlags(const PrimitiveTemplate *_this, const char *val, int *groupFlags);
void FX_Print(const char *msg, ...);
MaterialHandle FX_RegisterMaterial(const char *material);
Bool PrimitiveTemplate_ParseMaterials(const PrimitiveTemplate *_this, GPValue *grp);
Bool PrimitiveTemplate_ParseModels(const PrimitiveTemplate *_this, GPValue *grp);
Bool PrimitiveTemplate_ParseImpactFxStrings(const PrimitiveTemplate *_this, GPValue *grp);
Bool PrimitiveTemplate_ParseDeathFxStrings(const PrimitiveTemplate *_this, GPValue *grp);
Bool PrimitiveTemplate_ParseEmitterFxStrings(const PrimitiveTemplate *_this, GPValue *grp);
Bool PrimitiveTemplate_ParsePlayFxStrings(const PrimitiveTemplate *_this, GPValue *grp);
float FxRange_GetVal(const FxRange *_this);
void PrimitiveTemplate_Init(const PrimitiveTemplate *_this);
void PrimitiveTemplate_ParseChannelCurve(const PrimitiveTemplate *_this, GPValue *pairs, FxChannelId channel);
void PrimitiveTemplate_CreateBackCompatibleRotationDeltaCurve(const PrimitiveTemplate *_this, float initialValue, float keyScale, float lifetime, int channelId, float graphScale);
Bool PrimitiveTemplate_ParseFlags(const PrimitiveTemplate *_this, const char *line, const FxFlagEntry *flagEntries, int flagEntryCount);
Bool PrimitiveTemplate_ParseRotationDelta(const PrimitiveTemplate *_this, const char *val);
Bool PrimitiveTemplate_ParseVelocity(const PrimitiveTemplate *_this, const char *val);
Bool PrimitiveTemplate_ParseAcceleration(const PrimitiveTemplate *_this, const char *val);
Bool PrimitiveTemplate_ParseChannel(const PrimitiveTemplate *_this, BackCompatibleParameters *backCompatibleParameters, GPGroup *grp, FxChannelId channelId, const PrimitiveTemplate *_this_4, const char *val, const PrimitiveTemplate *_this_6, const char *val_7, const PrimitiveTemplate *_this_8, const char *val_9, const PrimitiveTemplate *_this_10, const char *val_11);
Bool PrimitiveTemplate_ParsePrimitiveInternal(const PrimitiveTemplate *_this, BackCompatibleParameters *backCompatibleParameters, GPGroup *grp);

void FX_InitServer(void);
void FX_SetSortGroup(Effect *fx);
int FX_GetCluster(const vec_t *origin);
void FX_CalcOrigin2(const PrimitiveTemplate *primTemp, vec_t *org, vec_t *org2, const vec_t *origin, vec3_t *ax);
Bool FX_GetBoneOrientation(const FxBoltInfo *bolt, orientation_t *orient);
void FX_AddScheduledEffects(const vec_t *start, const vec_t *end);
float FX_GetServerVisibility(const vec_t *start, const vec_t *end);
void FX_AddCameraShake(EffectPrimitive *prim, vec3_t *ax, const vec_t *origin, const int lateTime, const int indexInBatch);
void FX_AddFxRunner(EffectPrimitive *prim, vec3_t *ax, const vec_t *origin, const int lateTime, const int indexInBatch);
void FX_AddDecal(EffectPrimitive *prim, vec3_t *ax, const vec_t *origin, const int lateTime, const int indexInBatch);
void FX_DrawAll(void);
void FX_AddCloud(EffectPrimitive *prim, vec3_t *ax, const vec_t *origin, const int lateTime, const int indexInBatch);
void FX_AddFlash(EffectPrimitive *prim, vec3_t *ax, const vec_t *origin, const int lateTime, const int indexInBatch);
void FX_AddLight(EffectPrimitive *prim, vec3_t *ax, const vec_t *origin, const int lateTime, const int indexInBatch);
void FX_AddCylinder(EffectPrimitive *prim, vec3_t *ax, const vec_t *origin, const int lateTime, const int indexInBatch);
void FX_AddLine(EffectPrimitive *prim, vec3_t *ax, const vec_t *origin, const int lateTime, const int indexInBatch);
void FX_AddParticle(EffectPrimitive *prim, vec3_t *ax, const vec_t *origin, const int lateTime, const int indexInBatch);
void FX_AddTail(EffectPrimitive *prim, vec3_t *ax, const vec_t *origin, const int lateTime, const int indexInBatch);
void FX_AddEmitter(EffectPrimitive *prim, vec3_t *ax, const vec_t *origin, const int lateTime, const int indexInBatch);
void FX_AddOrientedParticle(EffectPrimitive *prim, vec3_t *ax, const vec_t *origin, const int lateTime, const int indexInBatch);
void FX_UpdateScheduledEffectsNonBolt(void);
void FX_UpdateScheduledEffectsBolt(void);
void FX_UpdateAllBolt(void);
void FX_Rewind(int time);
void FX_UpdateAllNonBolt(void);
void FX_DrawScheduledEffects(void);
int FX_Restore(MemoryFile *memFile);
int FX_Init(int rendererExists);
void FX_Free(int bRemoveTemplates);

const char *GPValue_GetTopValue(const GPValue *_this);
Bool GPValue_IsList(const GPValue *_this);
void GPGroup_SortObject(const GPGroup *_this, GPObject *object, GPObject **unsortedList, GPObject **sortedList, GPObject **lastObject);
void GPGroup_Clean(const GPGroup *_this);
void GenericParser2_GenericParser2(const GenericParser2 *_this);
char *TextPool_AllocText(const TextPool *_this, char *text, unsigned char addNULL, TextPool **poolPtr);
GPGroup *GPGroup_AddGroup(const GPGroup *_this, const char *name, TextPool **textPool);
void GPValue_AddValue(const GPValue *_this, const char *newValue, TextPool **textPool);
GPValue *GPGroup_AddPair(const GPGroup *_this, const char *name, const char *value, TextPool **textPool);
void ZN14GenericParser2D2Ev(GenericParser2 *_this);
void ZN14GenericParser2D1Ev(GenericParser2 *_this);
Bool GPGroup_Parse(const GPGroup *_this, char **dataPtr, TextPool **textPool);
Bool GenericParser2_Parse(const GenericParser2 *_this, char **dataPtr, int cleanFirst, int writeable);

#endif
