#include "common_types.h"

#if defined(__x86_64__)
typedef long BSSINT;
#else
typedef int BSSINT;
#endif

BSSINT sBuilderProcPtr;
BSSINT sControlValidationUPP;
unsigned char sControlKeyFilterUPP[120];
unsigned char sRectList[12];
BSSINT sSwapCount;
unsigned char sCaptureMedia[8];
BSSINT sMainWindow;
unsigned char sCaptureMovie[24];
unsigned char sCaptureName[256];
BSSINT sCaptureTrack;
BSSINT sCaptureRefNum;
BSSINT sDisplayID;
BSSINT sSystemGammaBlue;
BSSINT sSystemGammaGreen;
BSSINT sSystemGammaRed;
BSSINT sScreenContext;
BSSINT sDisplayRefreshRate;
BSSINT sDisplayDepth;
BSSINT sFadeToken;
BSSINT sInitialized;
unsigned char sDisplayRect[16];
BSSINT sMainDisplayID;
unsigned char sMainRect[120];
unsigned char sResult_00334980[2];
unsigned char sTested[1];
unsigned char hasAltiVec[1];
unsigned char hasAltiVecBeenDetermined[124];
BSSINT sDataFolderDirID;
BSSINT sExecutableDirID;
BSSINT sAppFolderDirID;
unsigned char sAppFolderVRefNum[20];
unsigned char sAppBundleRef[96];
unsigned char sSystemLock[128];
BSSINT sResult_00334b00;
BSSINT sResult_00334b04;
BSSINT sResult_00334b08;
BSSINT sResult_00334b0c;
unsigned char sResult_00334b10[8];
BSSINT sResult_00334b18;
BSSINT sResult_00334b1c;
BSSINT sResult_00334b20;
BSSINT sResult_00334b24;
BSSINT sResult_00334b28;
unsigned char sResult_00334b2c[84];
unsigned char sGlobalMouse[128];
unsigned char sCursorList[12];
BSSINT sCurrentCursor;
BSSINT sSavedWinCursor;
unsigned char sTimerRef[108];
unsigned char sCachedVKMap[128];
BSSINT sATI4CompsConverterABGR;
BSSINT sATI4CompsConverterARGB;
BSSINT sStdConverterABGR;
unsigned char sStdConverterARGB[116];
unsigned char sDirect3DInterface[128];
unsigned char sPointScale[128];
BSSINT sEventTargetRef;
unsigned char sSystemCursorVisible_00334e84[124];
unsigned char g_threadValues[20];
unsigned char threadId[108];
unsigned char value1[16384];
unsigned char g_com_error[96];
unsigned char va_info[2052];
BSSINT LittleFloatWrite;
BSSINT LittleFloatRead;
BSSINT LittleLong64;
BSSINT LittleLong;
BSSINT LittleShort;
unsigned char valueindex[8];
BSSINT iWeaponInfoSource;
BSSINT logfile;
unsigned char errorcode[120];
unsigned char com_errorMessage[4096];
BSSINT com_lastFrameTime;
BSSINT com_codeTimeScale;
unsigned char com_fullyInitialized[120];
unsigned char com_pushedEvents[6144];
BSSINT com_pushedEventsTail;
BSSINT com_pushedEventsHead;
BSSINT com_safemode;
BSSINT rd_flush;
BSSINT rd_buffersize;
BSSINT rd_buffer;
BSSINT opening_qconsole;
BSSINT printedWarning;
BSSINT timeClientFrame;
BSSINT errorCount;
unsigned char lastErrorTime[88];
unsigned char g_currentAsian[32];
unsigned char szErrorString[1024];
unsigned char szStrings[2048];
unsigned char iCurrString[96];
unsigned char iString[32];
unsigned char szIwdLanguageName[128];
unsigned char bLanguagesListed[96];
unsigned char g_largeLocalPos[128];
unsigned char g_largeLocalBuf[524288];
unsigned char hunk_high[8];
unsigned char hunk_low[8];
BSSINT s_hunkData;
BSSINT s_hunkTotal;
unsigned char com_hunkData[8];
unsigned char com_fileDataHashTable[4096];
unsigned char s_origHunkData[96];
unsigned char g_xAnimInfo[163840];
unsigned char g_notifyListSize[32];
unsigned char g_notifyList[1536];
unsigned char g_end[5];
unsigned char g_anim_developer[91];
unsigned char scrStringGlob[65664];
unsigned char scrMemTreeGlob[525184];
unsigned char info6[8192];
unsigned char info8[8192];
unsigned char info5[8192];
unsigned char info4[8192];
unsigned char info3[8192];
unsigned char info2[8192];
unsigned char buf_00482a80[1024];
unsigned char basename_00482e80[128];
unsigned char sString[128];
unsigned char sString_00482f80[64];
unsigned char sTemp[64];
unsigned char cmd_functions[128];
unsigned char cmd_argv[2048];
unsigned char cmd_argc[128];
unsigned char cmd_tokenized[8704];
unsigned char cmd_args1[1024];
unsigned char cmd_text_buf[65536];
unsigned char info2_00495f00[8192];
unsigned char info1[1024];
unsigned char dvarHashTable[1024];
unsigned char dvarVectorPool[48];
BSSINT dvarVectorIndex;
unsigned char dvar_cheats[12];
unsigned char dvarPool[46080];
unsigned char isDvarSystemActive[1];
unsigned char isLoadingAutoExecGlobalFlag[63];
unsigned char milesGlob[384];
unsigned char effectListArrayNonBolt[7296];
unsigned char effectListArrayBolt[7296];
unsigned char effectClusterArray[28800];
unsigned char visibleEffectsBolt[14400];
unsigned char visibleEffectsNonBolt[14400];
unsigned char effectTemplateArrayCount[32];
unsigned char effectTemplateArray[1120];
BSSINT g_bDObjInited;
unsigned char com_lastDObjIndex[124];
unsigned char serverObjMap[2048];
unsigned char clientObjMap[2304];
unsigned char objFreeCount[128];
unsigned char objAlloced[2048];
unsigned char objBuf[204800];
unsigned char g_empty[128];
unsigned char localization[32];
unsigned char language_buffer[4192];
BSSINT shouldQuitOnError;
unsigned char cml[124];
unsigned char bg_iNumAmmoTypes[32];
unsigned char bg_weapAmmoTypes[512];
unsigned char bg_iNumSharedAmmoCaps[32];
unsigned char bg_sharedAmmoCaps[512];
unsigned char bg_iNumWeapClips[32];
unsigned char bg_weapClips[544];
unsigned char scrVmGlob[8320];
unsigned char scrCompileGlob[512];
unsigned char scrAnimGlob[640];
BSSINT jump_height;
BSSINT jump_spreadAdd;
BSSINT jump_slowdownEnable;
BSSINT jump_ladderPushVel;
unsigned char jump_stepSize[112];
BSSINT mantle_enable;
BSSINT mantle_view_yawcap;
BSSINT s_mantleAnims;
BSSINT mantle_debug;
BSSINT mantle_check_angle;
BSSINT mantle_check_range;
unsigned char mantle_check_radius[104];
unsigned char token_004ed380[1024];
unsigned char statCount[32];
unsigned char stats[96];
unsigned char initialized[128];
unsigned char cm_world[24704];
unsigned char cinTable[7360];
unsigned char cin[2426400];
unsigned char ROQ_YY_tab[1024];
unsigned char ROQ_VG_tab[1024];
unsigned char ROQ_UG_tab[1024];
unsigned char ROQ_VR_tab[1024];
unsigned char ROQ_UB_tab[1024];
unsigned char vq2[32768];
unsigned char vq4[131072];
unsigned char vq8[524288];
unsigned char sAspyrIntroPlayed[32];
unsigned char g_testLods[128];
unsigned char szReference[1024];
unsigned char currentPos[128];
unsigned char bg_defaultWeaponDefs[1568];
unsigned char g_playerAnimTypeNames[256];
unsigned char g_playerAnimTypeNamesCount[96];
unsigned char sys_info[544];
unsigned char eventQue[6144];
BSSINT eventTail;
BSSINT eventHead;
BSSINT sys_configSum;
BSSINT sys_gpu;
BSSINT sys_sysMB;
unsigned char sys_cpuGHz[76];
BSSINT sConsoleEditText;
BSSINT sConsoleTextView;
BSSINT sConsoleData;
unsigned char sConsoleWindow[20];
unsigned char sReturnedText[512];
unsigned char sConsoleText[512];
unsigned char sTimerRef_007f1b20[96];
unsigned char cwd[256];
unsigned char lockPvsViewParms[332];
BSSINT warnCount;
unsigned char warnCount_007f1dd0[48];
unsigned char s_cmdList[128];
unsigned char s_debugFrameGlob[2399616];
unsigned char s_backEndData[2399596];
unsigned char g_dummyBuf[20];
unsigned char re[384];
BSSINT warnCount_00c85b00;
BSSINT warnCount_00c85b04;
BSSINT warnCount_00c85b08;
BSSINT warnCount_00c85b0c;
unsigned char warnCount_00c85b10[112];
unsigned char materialGlobals[10752];
unsigned char s_cache[50304];
unsigned char g_imageProgs[448];
unsigned char imageGlobals[8256];
unsigned char cubeShotGlob[24];
unsigned char lastNumber[104];
unsigned char s_vc_log[128];
unsigned char registeredFontCount[32];
unsigned char registeredFont[96];
unsigned char debugGlobals[128];
unsigned char dpvsConfig[32];
unsigned char dpvsGlob[224];
unsigned char dpvsScene[131200];
unsigned char shadowCookieGlob[128];
unsigned char waterGlob[196608];
unsigned char surfBoundsGlob[128];
unsigned char mtlLoadGlob[128];
unsigned char smodelLoadGlob[128];
unsigned char outdoorGlob[128];
unsigned char sOldButtonState[128];
BSSINT yaccResult;
BSSINT yy_start;
unsigned char yy_current_buffer[24];
unsigned char ch_buf[16388];
BSSINT g_dummyVal;
BSSINT g_parse_user;
BSSINT g_sourcePos;
BSSINT g_out_pos;
BSSINT yy_hold_char;
BSSINT yy_c_buf_p;
BSSINT yy_n_chars;
BSSINT yy_did_buffer_switch_on_eof;
BSSINT yy_last_accepting_cpos;
unsigned char yy_last_accepting_state[56];
BSSINT sSoundEngine;
unsigned char sHighQualityEngine[124];
unsigned char comBspGlob[128];
unsigned char __ZGVZ16GetMacGameEnginevE13theGameEngine[32];
unsigned char theGameEngine[96];
unsigned char sDeviceName[128];
unsigned char sShaderPrograms[24];
unsigned char sInit[104];
unsigned char hasExactMatch[128];
unsigned char shortestMatch[1024];
BSSINT matchCount;
BSSINT completionString;
unsigned char tinystr[120];
unsigned char cg_itemsArray[9216];
unsigned char cg_weaponsArray[55808];
unsigned char cg_entitiesArray[561152];

unsigned char cgsArray[sizeof(cgs_t)];
unsigned char cgArray[997788];
unsigned char g_mapLoaded[1];
unsigned char g_ambientStarted[3];
unsigned char buffer_00e86a20[1120];
unsigned char input_viewSensitivity[32];
unsigned char szServerIPAddress[128];
unsigned char recursive[96];
unsigned char g_sv_skel_memory_start[128];
unsigned char g_sv_skel_memory[262144];
unsigned char warnCount_00ec7000[128];
unsigned char g_gametype[64];
unsigned char g_mapname[64];
BSSINT g_ingameMenusLoaded;
unsigned char ui_serverFilterType[28];
unsigned char menuBuf2[32768];
unsigned char errorString[1024];
unsigned char info[1024];
BSSINT bypassKeyClear;
BSSINT numclean;
unsigned char lastTime[24];
unsigned char clientBuff[32];
unsigned char info_00ecf960[1024];
BSSINT numTimeOuts;
BSSINT numFound;
unsigned char tleIndex[24];
unsigned char loopbacks[45072];
unsigned char net_iProfilingOn[16];
unsigned char s[96];
unsigned char string_00edae00[1024];
unsigned char con[151588];
BSSINT con_outputWindowColor;
BSSINT con_outputSliderColor;
BSSINT con_outputBarColor;
BSSINT con_inputHintBoxColor;
unsigned char con_inputBoxColor[12];
unsigned char conDrawInputGlob[32];
unsigned char hudMsgIconMaterials[1024];
unsigned char registeredIconMaterialCount[32];
unsigned char s_playerMute[64];
unsigned char rconGlob[64];
BSSINT debugMode;
BSSINT captureData;
BSSINT captureFunc;
BSSINT itemCapture;
unsigned char g_bindItem[16];
unsigned char scrollInfo[32];
BSSINT lastListBoxClickTime;
unsigned char rect_00f00744[24];
unsigned char inHandleKey[36];
unsigned char initialized_00f00780[128];
unsigned char msgInit[32];
#if defined(__x86_64__)

struct huffman_t msgHuff;
#else
unsigned char msgHuff[57408];
#endif
unsigned char string_00f0e860[1024];
unsigned char string_00f0ec60[8192];
unsigned char string_00f10c60[1056];
unsigned char bigConfigString[8192];
BSSINT warnCount_00f13080;
unsigned char warnCount_00f13084[124];
unsigned char botport[128];
unsigned char ui_arenaInfos[256];
unsigned char ui_numArenas[128];
unsigned char defineBits[1152];
unsigned char weaponStrings[1024];
BSSINT parseEvent;
BSSINT parseMovetype;
unsigned char defineStringsOffset[24];
unsigned char numDefines[64];
unsigned char defineStrings[10016];
unsigned char defineStr[1152];
BSSINT g_piNumLoadAnims;
BSSINT g_pLoadAnims;
unsigned char globalScriptData[24];
unsigned char input[100000];
unsigned char bScriptFileLoaded[64];
unsigned char playersKb[640];
BSSINT hud_healthOverlay_phaseEnd_pulseDuration;
BSSINT hud_healthOverlay_phaseEnd_toAlpha;
BSSINT hud_healthOverlay_regenPauseTime;
BSSINT hud_healthOverlay_phaseThree_pulseDuration;
BSSINT hud_healthOverlay_phaseThree_toAlphaMultiplier;
BSSINT hud_healthOverlay_phaseTwo_pulseDuration;
BSSINT hud_healthOverlay_phaseTwo_toAlphaMultiplier;
BSSINT hud_healthOverlay_phaseOne_pulseDuration;
BSSINT hud_healthOverlay_pulseStart;
BSSINT hud_enable;
unsigned char hud_fadeout_speed[24];
unsigned char szErrorString_00f2f140[1088];
unsigned char spGlob[128];
unsigned char bloc[128];
unsigned char g_strHandle[8192];
BSSINT lasttime;
unsigned char adr[124];
unsigned char color_00f31700[128];
unsigned char line_00f31780[1024];
unsigned char menuBuf[32768];
unsigned char g_load[1600];
unsigned char menuParseKeywordHash[2048];
unsigned char menuBuf1[4096];
unsigned char string_00f3b9c0[4160];
unsigned char g_clients[665856];
BSSINT hud_flash_period_offhand;
unsigned char hud_flash_time_offhand[124];
unsigned char cached_models[1024];
unsigned char pushed[32768];
unsigned char pushed_p[128];
unsigned char turretInfo[2176];
unsigned char g_HitLocConstNames[128];
unsigned char numIPFilters[32];
unsigned char ipFilters[8288];
unsigned char str_00fea180[256];
unsigned char index_00fea280[128];
unsigned char rendererStats[64];
unsigned char fps_previousTimes[128];
BSSINT fps_index;
unsigned char previous[60];
unsigned char cg_pmove[248];
unsigned char cg_numTriggerEntities[8];
unsigned char cg_triggerEntities[1024];
unsigned char cg_numSolidEntities[128];
unsigned char cg_solidEntities[1024];
unsigned char cg_eachClientLocalEntities[24064];
BSSINT ip_socket;
unsigned char winsockInitialized[28];
unsigned char winsockdata[400];
BSSINT net_socksPassword;
BSSINT net_socksUsername;
BSSINT net_socksPort;
BSSINT net_socksServer;
BSSINT net_socksEnabled;
BSSINT net_noipx;
BSSINT net_noudp;
BSSINT networkingEnabled;
BSSINT socks_socket;
unsigned char socksRelayAddr[16];
unsigned char usingSocks[28];
unsigned char localIP[64];
unsigned char numIP[32];
unsigned char socksBuf[4096];
unsigned char ipx_socket[32];
unsigned char hackSize[128];
BSSINT currentRecordingSample;
unsigned char recording[28];
unsigned char s_clientTalkTime[256];
unsigned char s_clientSamples[256];
BSSINT playing_00ff20a0;
unsigned char count_00ff20a4[92];
unsigned char decodeBits[128];
unsigned char encodeBits[36];
unsigned char g_encoder[92];
BSSINT sAudioRecorder;
unsigned char g_current_sample[28];
unsigned char s_recordingSamples[2340];
unsigned char s_recordingSamplePtr[60];
unsigned char dsoundplay_initialized[128];
BSSINT g_High;
BSSINT g_Low;
unsigned char g_special[120];
unsigned char g_WarmOff[1];
unsigned char g_NoTextureID[127];
unsigned char __ZN6CFence15sUnusedFenceIDsE[128];
unsigned char __ZN13CMemoryBuffer20sDelayedFreeRequestsE[128];
unsigned char __ZN7COpenGL7sOpenGLE[4096];
unsigned char g_traceThreadInfo[28];
unsigned char com_consoleLines[128];
unsigned char com_numConsoleLines[8];
BSSINT ui_errorTitle;
BSSINT ui_errorMessage;
BSSINT com_fixedConsolePosition;
BSSINT com_errorEntered;
BSSINT com_frameNumber;
BSSINT com_frameTime;
BSSINT com_animCheck;
BSSINT com_recommendedSet;
BSSINT sv_paused;
BSSINT com_expectedHunkUsage;
BSSINT nextmap;
BSSINT cl_paused;
BSSINT com_introPlayed;
BSSINT shortversion;
BSSINT version_00ff3f60;
BSSINT com_logfile;
BSSINT com_sv_running;
BSSINT com_maxfps;
BSSINT com_fixedtime;
BSSINT com_timescaleValue;
BSSINT com_timescale;
BSSINT com_statmon;
BSSINT com_developer_script;
BSSINT com_developer;
unsigned char com_viewlog[120];
BSSINT loc_warningsAsErrors;
BSSINT loc_warnings;
BSSINT loc_translate;
BSSINT loc_forceEnglish;
unsigned char loc_language[16];
unsigned char lastValidGame[256];
unsigned char lastValidBase[256];
unsigned char fs_serverReferencedIwdNames[4096];
unsigned char fs_serverReferencedIwds[4096];
unsigned char fs_numServerReferencedIwds[32];
unsigned char fs_serverIwdNames[4096];
unsigned char fs_serverIwds[4096];
#if defined(__x86_64__)

fileHandleData_t fsh[74];
#else
unsigned char fsh[21016];
#endif
BSSINT fs_checksumFeed;
BSSINT fs_fakeChkSum;
BSSINT fs_ignoreLocalized;
BSSINT fs_restrict;
BSSINT fs_gameDirVar;
BSSINT fs_copyfiles;
BSSINT fs_cdpath;
BSSINT fs_useOldAssets;
BSSINT fs_basegame;
BSSINT fs_basepath;
BSSINT fs_homepath;
unsigned char fs_debug[28];
unsigned char fs_gamedir[256];
BSSINT fs_loadStack;
unsigned char com_fileAccessed[96];
unsigned char com_dedicated[128];
unsigned char scrMemTreePub[28];
unsigned char g_default[228];
BSSINT snd_touchStreamFilesOnLoad;
BSSINT snd_enableReverb;
BSSINT snd_enableStream;
BSSINT snd_enable3D;
BSSINT snd_enable2D;
BSSINT snd_slaveFadeTime;
BSSINT snd_volume;
BSSINT snd_stereo;
BSSINT snd_bits;
BSSINT snd_khz;
unsigned char snd_errorOnMissing[84];
#if defined(__x86_64__)

struct snd_local_t g_snd;
#else
unsigned char g_snd[5124];
#endif
unsigned char cmd_texts[12];
unsigned char cmd_wait[116];
BSSINT dvarCount;
BSSINT dvar_modifiedFlags;
unsigned char sortedDvars[116];
BSSINT mss_q3fs;
unsigned char mss_3d_provider[128];
BSSINT visibleEffectCountBolt;
unsigned char visibleEffectCountNonBolt[24];
unsigned char theFxHelpers[252];
BSSINT effectBlockSightCount;
BSSINT cullEffectCountNonBolt;
BSSINT cullEffectCountBolt;
BSSINT initialEffectActiveCountNonBolt;
BSSINT initialEffectActiveCountBolt;
BSSINT privateEffectActiveCountNonBolt;
BSSINT privateEffectActiveCountBolt;
BSSINT effectActiveCount;
BSSINT effectActiveCountNonBolt;
unsigned char effectActiveCountBolt[64];
unsigned char g_effectVisArray[36000];
BSSINT g_effectVisArrayCount;
BSSINT clusterSort;
unsigned char effectClusterCount[92];
unsigned char fx_camera_valid[128];
unsigned char fxSchedulers[128];
BSSINT player_dmgtimer_flinchTime;
BSSINT player_dmgtimer_stumbleTime;
BSSINT player_dmgtimer_minScale;
BSSINT player_dmgtimer_maxTime;
BSSINT player_dmgtimer_timePerPoint;
BSSINT player_turnAnims;
BSSINT player_spectateSpeedScale;
BSSINT player_backSpeedScale;
BSSINT player_strafeSpeedScale;
BSSINT player_footstepsThreshhold;
BSSINT player_moveThreshhold;
BSSINT player_adsExitDelay;
BSSINT player_scopeExitOnDamage;
BSSINT player_toggleBinoculars;
BSSINT player_breath_snd_delay;
BSSINT player_breath_snd_lerp;
BSSINT player_breath_gasp_lerp;
BSSINT player_breath_hold_lerp;
BSSINT player_breath_gasp_scale;
BSSINT player_breath_fire_delay;
BSSINT player_breath_gasp_time;
BSSINT player_breath_hold_time;
BSSINT bg_aimSpreadMoveSpeedThreshold;
BSSINT bg_bobMax;
BSSINT bg_bobAmplitudeProne;
BSSINT bg_bobAmplitudeDucked;
BSSINT bg_bobAmplitudeStanding;
BSSINT bg_swingSpeed;
BSSINT friction;
BSSINT stopspeed;
BSSINT inertiaAngle;
BSSINT inertiaDebug;
BSSINT inertiaMax;
BSSINT bg_fallDamageMaxHeight;
BSSINT bg_fallDamageMinHeight;
BSSINT bg_foliagesnd_resetinterval;
BSSINT bg_foliagesnd_fastinterval;
BSSINT bg_foliagesnd_slowinterval;
BSSINT bg_foliagesnd_maxspeed;
BSSINT bg_foliagesnd_minspeed;
BSSINT bg_prone_yawcap;
BSSINT bg_ladder_yawcap;
BSSINT player_view_pitch_down;
unsigned char player_view_pitch_up[112];
unsigned char cm[384];
unsigned char bg_weaponDefs[608];
unsigned char scrVmPub[17184];
unsigned char g_script_error_level[32];
unsigned char g_script_error[2400];
unsigned char scrVarPub[262240];
unsigned char scrVarGlob[1048608];
unsigned char scrCompilePub[65592];
unsigned char scrParserPub[28];
unsigned char scrParserGlob[128];
unsigned char scrAnimPub[1152];
#if defined(__x86_64__)

struct g_sa_type g_sa;
#else
unsigned char g_sa[6500];
#endif
unsigned char sys_timeBase[28];
unsigned char legacyHacksArray[1792];
unsigned char saLoadObjGlob[2272];
unsigned char giFilesFound[32];
unsigned char sourceFiles[256];
BSSINT globaldefines;
unsigned char numtokens[92];
unsigned char g_wv[32];
unsigned char sys_packetReceived[16480];
unsigned char scene[124292];
unsigned char frontEndDataOut[124];
unsigned char g_skinBuffers[40964];
BSSINT r_aspectRatio;
BSSINT r_rendererInUse;
BSSINT r_rendererPreference;
BSSINT r_displayRefresh;
BSSINT r_mode;
BSSINT r_monitor;
BSSINT r_fullscreen;
BSSINT r_sse_skinning;
BSSINT sys_SSE;
BSSINT developer;
BSSINT vid_ypos;
BSSINT vid_xpos;
BSSINT r_testFillEnable;
BSSINT r_testFill;
BSSINT r_testTransform;
BSSINT r_sun_from_dvars;
BSSINT r_outdoorFeather;
BSSINT r_outdoorDownBias;
BSSINT r_outdoorAwayBias;
BSSINT r_glowBloomDesaturation;
BSSINT r_glowBloomCutoff;
unsigned char r_glowBloomIntensity[8];
unsigned char r_glowSkyBleedIntensity[8];
unsigned char r_glowRadius[8];
BSSINT r_glow;
BSSINT r_distortion;
BSSINT r_blur;
BSSINT sc_offscreenCasterLodScale;
BSSINT sc_offscreenCasterLodBias;
BSSINT sc_length;
BSSINT sc_shadowOutRate;
BSSINT sc_shadowInRate;
BSSINT sc_fadeRange;
BSSINT sc_wantCountMargin;
BSSINT sc_wantCount;
BSSINT sc_showDebug;
BSSINT sc_showOverlay;
BSSINT sc_debugReceiverCount;
BSSINT sc_debugCasterCount;
BSSINT sc_count;
BSSINT sc_blur;
BSSINT sc_enable;
BSSINT r_forceLod;
BSSINT r_lowestLodDist;
BSSINT r_lowLodDist;
BSSINT r_mediumLodDist;
BSSINT r_highLodDist;
BSSINT r_showGroundLit;
BSSINT r_showFloatZDebug;
BSSINT r_showFbColorDebug;
BSSINT r_showSModelNames;
BSSINT r_showPortals;
BSSINT r_portalMinClipArea;
BSSINT r_portalWalkLimit;
BSSINT r_singleCell;
BSSINT r_portalBevelsOnly;
BSSINT r_portalBevels;
BSSINT r_portalFineCull;
BSSINT r_pvsStats;
BSSINT r_skipPvs;
BSSINT r_lockPvs;
BSSINT r_depthPrepassModels;
BSSINT r_drawWater;
BSSINT r_drawPrimFloor;
BSSINT r_drawPrimCap;
unsigned char r_dlightLimit[8];
BSSINT r_drawXModels;
BSSINT r_drawSModels;
BSSINT r_drawBModels;
BSSINT r_drawEntities;
BSSINT r_drawDecals;
BSSINT r_drawWorld;
BSSINT r_drawSun;
BSSINT r_clearColor2;
BSSINT r_clearColor;
BSSINT r_aaSamples;
BSSINT r_aaAlpha;
BSSINT r_swapInterval;
BSSINT r_norefresh;
BSSINT r_skipBackEnd;
BSSINT r_logFile;
BSSINT r_objectiveColorDx7Max;
BSSINT r_objectiveColorDx7Min;
BSSINT r_lightTweakSunDirection;
BSSINT r_lightTweakSunDiffuseColor;
BSSINT r_lightTweakSunColor;
BSSINT r_lightTweakAmbientColor;
BSSINT r_lightTweakSunLight;
BSSINT r_lightTweakDiffuseFraction;
BSSINT r_lightTweakAmbient;
BSSINT r_showMissingLightGrid;
BSSINT r_showLightGrid;
BSSINT r_vc_showlog;
BSSINT r_vc_makelog;
BSSINT r_railCoreWidth;
BSSINT r_xdebug;
BSSINT r_showVertCounts;
BSSINT r_showSurfCounts;
BSSINT r_showTriCounts;
BSSINT r_showTris;
BSSINT r_cosinePowerMapShift;
BSSINT r_specularColorScale;
BSSINT r_specularMap;
BSSINT r_normalMap;
BSSINT r_colorMap;
BSSINT r_lightMap;
BSSINT r_picmip_spec;
BSSINT r_picmip_bump;
BSSINT r_picmip;
BSSINT r_picmip_manual;
BSSINT r_polygonOffsetBias;
BSSINT r_polygonOffsetScale;
BSSINT r_fog;
BSSINT r_zfar;
BSSINT r_znear_depthhack;
BSSINT r_znear;
BSSINT r_lodBias;
BSSINT r_lodScale;
BSSINT r_smc_enable;
BSSINT r_skinCache;
BSSINT r_multiGpu;
BSSINT r_gpuSync;
BSSINT r_optimizeXModels;
BSSINT r_optimizeLightmaps;
BSSINT r_optimize;
BSSINT r_debugEntCounts;
BSSINT r_debugShader;
BSSINT r_fullbright;
BSSINT r_anisotropy;
BSSINT r_textureMode;
BSSINT r_ignoreHwGamma;
BSSINT r_gamma;
BSSINT r_overbrightBits;
unsigned char r_ignore[120];
unsigned char dx[11744];
unsigned char vidConfig[64];
unsigned char ri[576];
unsigned char rg[12800];
unsigned char rgp[4336];
unsigned char g_disableRendering[16];
unsigned char dxState[8580];
unsigned char g_FenceID[124];
unsigned char tess[370688];
unsigned char backEnd[224912];
unsigned char backEndData[16];
unsigned char sunFlareArray[228];
unsigned char rgl[28];
unsigned char s_world[640];
unsigned char lightGlob[352];
unsigned char delayedGroup[260];
BSSINT r_sun_fx_position;
BSSINT r_sunglare_fadeout;
BSSINT r_sunglare_fadein;
BSSINT r_sunglare_max_lighten;
BSSINT r_sunglare_max_angle;
BSSINT r_sunglare_min_angle;
BSSINT r_sunblind_fadeout;
BSSINT r_sunblind_fadein;
BSSINT r_sunblind_max_darken;
BSSINT r_sunblind_max_angle;
BSSINT r_sunblind_min_angle;
BSSINT r_sunflare_fadeout;
BSSINT r_sunflare_fadein;
BSSINT r_sunflare_max_alpha;
BSSINT r_sunflare_max_angle;
BSSINT r_sunflare_max_size;
BSSINT r_sunflare_min_angle;
BSSINT r_sunflare_min_size;
BSSINT r_sunflare_shader;
BSSINT r_sunsprite_size;
unsigned char r_sunsprite_shader[44];
BSSINT yytext;
BSSINT yyleng;
BSSINT yynerrs;
unsigned char yylval[8];
unsigned char yychar[108];
BSSINT ui_playerProfileAlreadyChosen;
unsigned char com_playerProfile[124];
unsigned char __ZN10CVAOPacket14sGenericPacketE[688];
unsigned char __ZN10CVAOPacket11sAllPacketsE[80];
unsigned char __ZN12CStreamSound10sQTStreamsE[128];
unsigned char playerKeys[3392];
unsigned char g_consoleField[280];
BSSINT historyLine;
BSSINT nextHistoryLine;
unsigned char historyEditLines[8992];
BSSINT cg_weaponrightbone;
BSSINT cg_weaponleftbone;
BSSINT cg_blood;
BSSINT cg_headIconMinScreenRadius;
BSSINT cg_constantSizeHeadIcons;
BSSINT cg_voiceIconSize;
BSSINT cg_connectionIconSize;
BSSINT cg_scriptIconSize;
BSSINT cg_youInKillCamSize;
BSSINT cg_shock_mouse_fadeTime;
BSSINT cg_shock_mouse_sensitivityscale;
BSSINT cg_shock_mouse_maxyawspeed;
BSSINT cg_shock_mouse_maxpitchspeed;
BSSINT cg_shock_mouse;
BSSINT cg_shock_volume_shellshock;
BSSINT cg_shock_volume_announcer;
BSSINT cg_shock_volume_music;
BSSINT cg_shock_volume_local;
BSSINT cg_shock_volume_body;
BSSINT cg_shock_volume_item;
BSSINT cg_shock_volume_voice;
BSSINT cg_shock_volume_weapon;
BSSINT cg_shock_volume_menu;
BSSINT cg_shock_volume_auto2d;
BSSINT cg_shock_volume_auto;
BSSINT cg_shock_soundModEndDelay;
BSSINT cg_shock_soundWetLevel;
BSSINT cg_shock_soundDryLevel;
BSSINT cg_shock_soundRoomType;
BSSINT cg_shock_soundLoopEndDelay;
BSSINT cg_shock_soundLoopFadeTime;
BSSINT cg_shock_soundFadeOutTime;
BSSINT cg_shock_soundFadeInTime;
BSSINT cg_shock_sound;
BSSINT cg_shock_viewKickRadius;
BSSINT cg_shock_viewKickFadeTime;
BSSINT cg_shock_viewKickPeriod;
BSSINT cg_shock_screenBlendFadeTime;
BSSINT cg_shock_screenBlendTime;
BSSINT cg_scoreboardItemHeight;
BSSINT cg_scoreboardBannerHeight;
BSSINT cg_scoreboardScrollStep;
BSSINT cg_drawGameMessages;
BSSINT cg_gameBoldMessageWidth;
BSSINT cg_gameMessageWidth;
BSSINT cg_subtitleCharHeight;
BSSINT cg_subtitlePosY;
BSSINT cg_subtitlePosX;
BSSINT cg_subtitleWidthWidescreen;
BSSINT cg_subtitleWidthStandard;
BSSINT cg_subtitleMinTime;
BSSINT cg_subtitles;
BSSINT cg_minicon;
BSSINT cg_developer;
BSSINT cg_dumpAnims;
BSSINT cg_descriptiveText;
BSSINT cg_voiceSpriteTime;
BSSINT cg_noTaunt;
BSSINT cg_predictItems;
BSSINT cg_paused;
BSSINT cg_chatHeight;
BSSINT cg_chatTime;
BSSINT cg_synchronousClients;
BSSINT cg_thirdPersonAngle;
BSSINT cg_thirdPersonRange;
BSSINT cg_thirdPerson;
BSSINT cg_fovMin;
BSSINT cg_fovScale;
BSSINT cg_fov;
BSSINT cg_tracerScaleDistRange;
BSSINT cg_tracerScaleMinDist;
BSSINT cg_tracerScale;
BSSINT cg_tracerSpeed;
BSSINT cg_tracerLength;
BSSINT cg_tracerWidth;
BSSINT cg_tracerChance;
BSSINT cg_gun_move_minspeed;
BSSINT cg_gun_move_rate;
BSSINT cg_gun_ofs_u;
BSSINT cg_gun_ofs_r;
BSSINT cg_gun_ofs_f;
BSSINT cg_gun_move_u;
BSSINT cg_gun_move_r;
BSSINT cg_gun_move_f;
BSSINT cg_gun_z;
BSSINT cg_gun_y;
BSSINT cg_gun_x;
BSSINT cg_hintFadeTime;
BSSINT cg_cursorHints;
BSSINT cg_drawGun;
BSSINT cg_viewsize;
BSSINT cg_brass;
BSSINT cg_marksLimit;
BSSINT cg_marks;
BSSINT cg_footsteps;
BSSINT cg_showmiss;
BSSINT cg_nopredict;
BSSINT cg_errorDecay;
BSSINT cg_debugEvents;
BSSINT cg_debugPosition;
BSSINT cg_drawMantleHint;
BSSINT cg_drawBreathHint;
BSSINT cg_drawHealth;
BSSINT cg_teamChatsOnly;
BSSINT cg_draw2D;
BSSINT cg_crosshairEnemyColor;
BSSINT cg_crosshairDynamic;
BSSINT cg_crosshairAlphaMin;
BSSINT cg_crosshairAlpha;
BSSINT cg_weaponCycleDelay;
BSSINT cg_drawLagometer;
BSSINT cg_hudProneY;
BSSINT cg_centerPrintY;
BSSINT cg_hudSayPosition;
BSSINT cg_hudChatPosition;
BSSINT cg_hudGrenadePointerPulseMin;
BSSINT cg_hudGrenadePointerPulseMax;
BSSINT cg_hudGrenadePointerPulseFreq;
BSSINT cg_hudGrenadePointerPivot;
BSSINT cg_hudGrenadePointerWidth;
BSSINT cg_hudGrenadePointerHeight;
BSSINT cg_hudGrenadeIconWidth;
BSSINT cg_hudGrenadeIconHeight;
BSSINT cg_hudGrenadeIconOffset;
BSSINT cg_hudGrenadeIconMaxHeight;
BSSINT cg_hudGrenadeIconMaxRange;
BSSINT cg_hudGrenadeIconInScope;
BSSINT cg_hudDamageIconInScope;
BSSINT cg_hudDamageIconTime;
BSSINT cg_hudDamageIconOffset;
BSSINT cg_hudDamageIconHeight;
BSSINT cg_hudDamageIconWidth;
BSSINT cg_hudStanceHintPrints;
BSSINT cg_hudStanceFlash;
BSSINT cg_hudObjectiveMinAlpha;
BSSINT cg_hudObjectiveMaxRange;
BSSINT cg_hudObjectiveMinHeight;
BSSINT cg_hudCompassSoundPingFadeTime;
BSSINT cg_hudCompassSpringyPointers;
BSSINT cg_hudCompassMinRadius;
BSSINT cg_hudCompassMinRange;
BSSINT cg_hudCompassMaxRange;
BSSINT cg_hudCompassSize;
BSSINT cg_drawCrosshairNamesPosY;
BSSINT cg_drawCrosshairNamesPosX;
BSSINT cg_drawCrosshairNames;
BSSINT cg_drawTurretCrosshair;
BSSINT cg_drawCrosshair;
BSSINT cg_drawSnapshot;
BSSINT cg_drawScriptUsage;
BSSINT cg_drawSoundOverlay;
BSSINT cg_drawMaterial;
BSSINT cg_drawFPS;
unsigned char cg_centertime[32];
unsigned char cgDC[640];
BSSINT old_com_frameTime;
unsigned char frame_msec[28];
unsigned char re_0121c6a0[352];
unsigned char cl_pinglist[16704];
unsigned char g_waitingForServer[32];
unsigned char cls[2755264];

unsigned char clientConnections[sizeof(clientConnection_t)];

unsigned char clients[1662356];
BSSINT cl_voice;
BSSINT name_01683858;
BSSINT nextdemo;
BSSINT cl_ingame;
BSSINT fx_profile;
BSSINT fx_visMinTraceDist;
BSSINT fx_count;
BSSINT fx_freeze;
BSSINT fx_debugBolt;
BSSINT fx_debug;
BSSINT fx_sort;
BSSINT fx_cull;
BSSINT fx_draw;
BSSINT fx_enable;
BSSINT cl_serverStatusResendTime;
unsigned char cl_inGameVideo[8];
BSSINT cl_allowDownload;
BSSINT cl_motdString;
BSSINT cl_activeAction;
BSSINT m_filter;
BSSINT m_side;
BSSINT m_forward;
BSSINT m_yaw;
BSSINT m_pitch;
BSSINT cl_showMouseRate;
BSSINT cl_mouseAccel;
BSSINT cl_sensitivity;
BSSINT cl_freelook;
BSSINT cl_forceavidemo;
BSSINT cl_avidemo;
BSSINT cl_showServerCommands;
BSSINT cl_showSend;
BSSINT cl_shownuments;
BSSINT cl_freezeDemo;
BSSINT cl_showTimeDelta;
BSSINT cl_packetdup;
BSSINT cl_maxpackets;
BSSINT cl_connectTimeout;
BSSINT cl_timeout;
BSSINT cl_noprint;
unsigned char cl_nodelta[8];
unsigned char gameInitialized[128];
BSSINT ui_playerProfileNameNew;
BSSINT ui_playerProfileSelected;
BSSINT ui_playerProfileCount;
BSSINT ui_serverStatusTimeOut;
BSSINT ui_currentMap;
BSSINT ui_browserKillcam;
BSSINT ui_browserFriendlyfire;
BSSINT ui_browserMod;
BSSINT ui_browserShowDedicated;
BSSINT ui_browserShowPure;
BSSINT ui_browserShowNoPassword;
BSSINT ui_browserShowPassword;
BSSINT ui_browserShowEmpty;
BSSINT ui_browserShowFull;
BSSINT ui_currentNetMap;
BSSINT ui_dedicated;
BSSINT ui_joinGameType;
BSSINT ui_netGameTypeName;
BSSINT ui_netGameType;
unsigned char ui_netSource[8];
BSSINT ui_extraBigFont;
BSSINT ui_bigFont;
BSSINT ui_smallFont;
unsigned char ui_gametype[32];
unsigned char uiInfoArray[4288];
unsigned char sharedUiInfo[115392];
BSSINT net_lanauthorize;
BSSINT net_showprofile;
BSSINT net_profile;
BSSINT packetDebug;
BSSINT showdrop;
unsigned char showpackets[108];
BSSINT sv_allowedClan2;
BSSINT sv_allowedClan1;
BSSINT sv_referencedIwdNames;
BSSINT sv_referencedIwds;
BSSINT sv_iwdNames;
BSSINT sv_iwds;
BSSINT sv_voiceQuality;
BSSINT sv_voice;
BSSINT sv_disableClientConsole;
BSSINT sv_kickBanTime;
BSSINT sv_mapRotationCurrent;
BSSINT sv_mapRotation;
BSSINT sv_showAverageBPS;
BSSINT sv_packet_info;
BSSINT sv_showCommands;
BSSINT sv_allowAnonymous;
BSSINT sv_cheats;
BSSINT sv_floodProtect;
BSSINT sv_pure;
BSSINT sv_debugReliableCmds;
BSSINT sv_debugRate;
BSSINT sv_gametype;
BSSINT sv_maxPing;
BSSINT sv_minPing;
BSSINT sv_maxRate;
BSSINT sv_serverid;
BSSINT sv_mapname;
BSSINT sv_padPackets;
BSSINT sv_reconnectlimit;
BSSINT sv_hostname;
BSSINT sv_privateClients;
BSSINT sv_maxclients;
BSSINT sv_allowDownload;
BSSINT sv_privatePassword;
BSSINT rcon_password;
BSSINT sv_zombietime;
BSSINT sv_timeout;
unsigned char sv_fps[108];
#if defined(__x86_64__)

server_t sv;
serverStatic_t svs;
#else
unsigned char sv[390528];
unsigned char svs[41216];
#endif
BSSINT con_restricted;
BSSINT con_miniconlines;
BSSINT con_minicontime;
BSSINT con_boldgamemessagetime;
unsigned char con_gamemessagetime[16];
unsigned char cl_serverStatusList[131680];
unsigned char scr_initialized[128];
unsigned char markVerts[69632];
unsigned char cg_markPolys[663552];
unsigned char cg_freeMarkPolys[128];
unsigned char buf_017dd900[128];
BSSINT cl_bypassMouseInput;
BSSINT cl_talking;
BSSINT cl_anglespeedkey;
BSSINT cl_pitchspeed;
unsigned char cl_yawspeed[16];
BSSINT cl_stanceHoldTime;
unsigned char cl_analog_attack_threshold[92];
BSSINT hud_deathQuoteFadeTime;
BSSINT hud_health_pulserate_critical;
BSSINT hud_health_pulserate_injured;
BSSINT hud_health_startpulse_critical;
BSSINT hud_health_startpulse_injured;
BSSINT hud_fade_offhand;
BSSINT hud_fade_stance;
BSSINT hud_fade_compass;
BSSINT hud_fade_healthbar;
unsigned char hud_fade_ammodisplay[92];
unsigned char g_scr_data[14080];
unsigned char itemParseKeywordHash[2048];
BSSINT g_dumpAnims;
BSSINT g_voteAbstainWeight;
BSSINT g_oldVoting;
BSSINT g_antilag;
BSSINT player_meleeHeight;
BSSINT player_meleeWidth;
BSSINT player_meleeRange;
BSSINT g_friendlyNameDist;
BSSINT g_friendlyfireDist;
BSSINT g_debugLocDamage;
BSSINT g_NoScriptSpam;
BSSINT g_TeamColor_Axis;
BSSINT g_TeamColor_Allies;
BSSINT g_TeamName_Axis;
BSSINT g_TeamName_Allies;
BSSINT g_ScoresBanner_Spectators;
BSSINT g_ScoresBanner_None;
BSSINT g_ScoresBanner_Axis;
BSSINT g_ScoresBanner_Allies;
unsigned char g_smoothClients[8];
int g_banIPs = 0;
#ifdef __EMSCRIPTEN__

extern int g_banIPs_dvar __attribute__((alias("g_banIPs")));
#else
__asm__(".globl g_banIPs_dvar\n.set g_banIPs_dvar, g_banIPs\n");
#endif
BSSINT g_listEntity;
unsigned char g_deadChat[8];
BSSINT g_allowVote;
BSSINT g_logSync;
BSSINT g_log;
BSSINT g_voiceChatTalkingDuration;
BSSINT voice_deadChat;
BSSINT voice_global;
BSSINT voice_localEcho;
BSSINT g_mantleBlockTimeBuffer;
BSSINT g_clonePlayerMaxVelocity;
BSSINT g_dropUpSpeedRand;
BSSINT g_dropUpSpeedBase;
BSSINT g_dropForwardSpeed;
BSSINT g_playerCollisionEjectSpeed;
BSSINT g_synchronousClients;
BSSINT g_motd;
BSSINT g_maxDroppedWeapons;
BSSINT g_weaponAmmoPools;
BSSINT g_debugBullets;
BSSINT g_debugDamage;
BSSINT g_inactivity;
BSSINT g_useholdspawndelay;
BSSINT g_useholdtime;
BSSINT g_knockback;
BSSINT g_cheats;
BSSINT g_gravity;
BSSINT g_speed;
BSSINT g_dedicated;
BSSINT g_maxclients;
BSSINT g_password;
unsigned char g_gametype_017e1a58[40];
unsigned char g_entities[573440];
unsigned char level_bgs[813568];
unsigned char level[13952];
unsigned char itemRegistered[1024];
unsigned char g_hudelems[143392];
unsigned char __ZN12UI_Component1gE[224];
unsigned char g_fHitLocDamageMult[128];
unsigned char scr_const[256];
unsigned char lagometer[1664];
unsigned char cl_connectedToPureServer[128];
BSSINT removeMeWhenMPStopsCrashingInHere;
unsigned char ejectBrassCasingOrigin[124];
BSSINT cg_freeLocalEntities;
unsigned char cg_eachClientFreeLocalEntities[28];
unsigned char cg_eachClientActiveLocalEntities[224];
unsigned char levelSamples[24];
unsigned char voice_current_voicelevel[8];
unsigned char old_rec_source[256];
BSSINT mic_current_reclevel;
BSSINT mic_old_reclevel;
unsigned char winvoice_mic_scaler[8];
BSSINT winvoice_save_voice;
BSSINT winvoice_mic_reclevel;
unsigned char winvoice_mic_mute[72];
unsigned char partial_audio_buffer[1280];
unsigned char enc_buffer[4096];
unsigned char g_decode_frame_size[128];
unsigned char current_audioCallback[128];
BSSINT catch_exception_raise;
BSSINT catch_exception_raise_state;
BSSINT catch_exception_raise_state_identity;
BSSINT clock_alarm_reply;
BSSINT do_mach_notify_dead_name;
BSSINT do_mach_notify_no_senders;
BSSINT do_mach_notify_port_deleted;
BSSINT do_mach_notify_send_once;
BSSINT do_seqnos_mach_notify_dead_name;
BSSINT do_seqnos_mach_notify_no_senders;
BSSINT do_seqnos_mach_notify_port_deleted;
BSSINT do_seqnos_mach_notify_send_once;
BSSINT receive_samples;
